### ISSUE TITLE
Issue when setting temperature range.

### ISSUE THREAD

**Issue by hjdhjd** [chrisjshull/homebridge-nest#102]
I keep running into issues when I have a temperature range defined on my Nest (the "mode" to "Heat * Cool"). Any ideas?

Here's the log in question:
```
[7/21/2019, 5:05:27 PM] [Nest Platform] Setting cooling threshold temperature for Home to: 80
[7/21/2019, 5:05:27 PM] [Nest Platform] Setting heating threshold temperature for Home to: 62
[7/21/2019, 5:05:27 PM] [Nest Platform] Setting target temperature for Home to: 71
[7/21/2019, 5:05:27 PM] [Nest Platform] Cooling threshold temperature set to 26.6 Error: not_supported
    at Connection.update (/usr/local/lib/node_modules/homebridge-nest/lib/nest-connection.js:283:31)
    at NestThermostatAccessory.NestDeviceAccessory.updateDevicePropertyAsync (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:117:22)
    at NestThermostatAccessory.updateTargetWithCorrectUnitsAsync (/usr/local/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:400:17)
    at NestThermostatAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:388:17)
    at invokeFunc (/usr/local/lib/node_modules/homebridge-nest/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (/usr/local/lib/node_modules/homebridge-nest/node_modules/lodash.debounce/index.js:207:14)
    at Timeout.timerExpired [as _onTimeout] (/usr/local/lib/node_modules/homebridge-nest/node_modules/lodash.debounce/index.js:195:14)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[7/21/2019, 5:05:27 PM] [Nest Platform] Heating threshold temperature set to 16.5 Error: not_supported
    at Connection.update (/usr/local/lib/node_modules/homebridge-nest/lib/nest-connection.js:283:31)
    at NestThermostatAccessory.NestDeviceAccessory.updateDevicePropertyAsync (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:117:22)
    at NestThermostatAccessory.updateTargetWithCorrectUnitsAsync (/usr/local/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:400:17)
    at NestThermostatAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:393:10)
    at invokeFunc (/usr/local/lib/node_modules/homebridge-nest/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (/usr/local/lib/node_modules/homebridge-nest/node_modules/lodash.debounce/index.js:207:14)
    at Timeout.timerExpired [as _onTimeout] (/usr/local/lib/node_modules/homebridge-nest/node_modules/lodash.debounce/index.js:195:14)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[7/21/2019, 5:05:27 PM] [Nest Platform] Temperature set to 21.5 Error: not_supported
    at Connection.update (/usr/local/lib/node_modules/homebridge-nest/lib/nest-connection.js:283:31)
    at NestThermostatAccessory.NestDeviceAccessory.updateDevicePropertyAsync (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:117:22)
    at NestThermostatAccessory.updateTargetWithCorrectUnitsAsync (/usr/local/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:400:17)
    at /usr/local/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:383:36
    at tryCatcher (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:439:21)

```

**Comment by adriancable** [comment]
Can you kindly run: homebridge -D

 

Then tell me the sequence of steps to reproduce, and send the log. Thanks!

**Comment by hjdhjd** [comment]
Here's a run from just now...

So the sequence of steps...

Thermostat begins in the 'Cool' mode.
Set Thermostat to 'Auto' in Home app.
Adjust the lower temperature bound down (in my case from 66 to 61)
Wait for boom
Set Thermostat to 'Cool' in Home app.

I can recreate it on-demand.

```
[7/22/2019, 10:21:44 PM] [Nest Platform] Setting target heating cooling for Home to: heat-cool
[7/22/2019, 10:21:45 PM] [Nest Platform] Target heating/cooling state for Home is: Auto
[7/22/2019, 10:21:47 PM] [Nest Platform] Target temperature for Home is: 21.2 °C and 70.16 °F
[7/22/2019, 10:21:57 PM] [Nest Platform] Queuing to set temperature 18.7
[7/22/2019, 10:21:57 PM] [Nest Platform] Target temperature for Home is: 18.7 °C and 65.66 °F
[7/22/2019, 10:21:57 PM] [Nest Platform] Queuing to set cooling threshold temperature 21.2
[7/22/2019, 10:21:57 PM] [Nest Platform] Queuing to set heating threshold temperature 16.2
[7/22/2019, 10:21:57 PM] [Nest Platform] Heating threshold temperature for Home is: 16.2 °C and 61.16 °F
[7/22/2019, 10:22:02 PM] [Nest Platform] Setting cooling threshold temperature for Home to: 70
[7/22/2019, 10:22:02 PM] [Nest Platform] Setting heating threshold temperature for Home to: 61
[7/22/2019, 10:22:02 PM] [Nest Platform] Setting target temperature for Home to: 66
[7/22/2019, 10:22:02 PM] [Nest Platform] Cooling threshold temperature set to 21.2 Error: not_supported
    at Connection.update (/usr/local/lib/node_modules/homebridge-nest/lib/nest-connection.js:283:31)
    at NestThermostatAccessory.NestDeviceAccessory.updateDevicePropertyAsync (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:117:22)
    at NestThermostatAccessory.updateTargetWithCorrectUnitsAsync (/usr/local/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:400:17)
    at NestThermostatAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:388:17)
    at invokeFunc (/usr/local/lib/node_modules/homebridge-nest/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (/usr/local/lib/node_modules/homebridge-nest/node_modules/lodash.debounce/index.js:207:14)
    at Timeout.timerExpired [as _onTimeout] (/usr/local/lib/node_modules/homebridge-nest/node_modules/lodash.debounce/index.js:195:14)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[7/22/2019, 10:22:02 PM] [Nest Platform] Heating threshold temperature set to 16.2 Error: not_supported
    at Connection.update (/usr/local/lib/node_modules/homebridge-nest/lib/nest-connection.js:283:31)
    at NestThermostatAccessory.NestDeviceAccessory.updateDevicePropertyAsync (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:117:22)
    at NestThermostatAccessory.updateTargetWithCorrectUnitsAsync (/usr/local/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:400:17)
    at NestThermostatAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:393:10)
    at invokeFunc (/usr/local/lib/node_modules/homebridge-nest/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (/usr/local/lib/node_modules/homebridge-nest/node_modules/lodash.debounce/index.js:207:14)
    at Timeout.timerExpired [as _onTimeout] (/usr/local/lib/node_modules/homebridge-nest/node_modules/lodash.debounce/index.js:195:14)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[7/22/2019, 10:22:02 PM] [Nest Platform] Temperature set to 18.7 Error: not_supported
    at Connection.update (/usr/local/lib/node_modules/homebridge-nest/lib/nest-connection.js:283:31)
    at NestThermostatAccessory.NestDeviceAccessory.updateDevicePropertyAsync (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:117:22)
    at NestThermostatAccessory.updateTargetWithCorrectUnitsAsync (/usr/local/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:400:17)
    at /usr/local/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:383:36
    at tryCatcher (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:439:21)
[7/22/2019, 10:22:07 PM] [Nest Platform] Target temperature for Home is: 21.2 °C and 70.16 °F
[7/22/2019, 10:22:07 PM] [Nest Platform] Heating threshold temperature for Home is: 19.1 °C and 66.38 °F
[7/22/2019, 10:22:24 PM] [Nest Platform] Setting target heating cooling for Home to: cool
[7/22/2019, 10:22:24 PM] [Nest Platform] Target heating/cooling state for Home is: Cool
[7/22/2019, 10:22:27 PM] [Nest Platform] Target temperature for Home is: 21.1 °C and 69.98 °F
^C[7/22/2019, 10:22:37 PM] Got SIGINT, shutting down Homebridge...

```

**Comment by adriancable** [comment]
First of all please can you check you have the latest commit from Github. I've recoded a lot of things in this area in the past day so let's first make sure you're on the latest version.

If it still doesn't work, please can you give me more detail in the steps to reproduce than the above ... something like the following:

1. Thermostat begins in 'Cool' mode. Temperature is set to X degrees.
2. Set Thermostat to 'Auto' mode in Home app. Temperature range is reported as X - Y degrees.
3. Adjust the lower temperature bound down to X degrees.
4. Wait for error

Thanks!

**Comment by hjdhjd** [comment]
Latest git version solved the issue for me. I even tried to force some edge cases and everything worked well. Thanks!

**Comment by adriancable** [comment]
Great! Closing for now.
