### ISSUE TITLE
plugin cannot find email/password

### ISSUE THREAD

**Issue by Johnyee1** [chrisjshull/homebridge-nest#127]
After properly configuring the JSON file, terminal return the error message "Error: You did not specify your Nest app {'email','password'} in config.json"

**To Reproduce**
1. a clean install of node 12.8, Homebridge 0.4.50, and nest plugin 3.2.4
2. Configure config.json
3. Run Homebridge

config.json file configured as follow:

{
"bridge": {
  "name": "Homebridge",
  "username": "CC:22:3D:E3:CE:30",
  "port": 51826,
  "pin": "031-45-154"
},

"description": "Homebridge configured",

"platforms": [
  {
    "platform": "Nest",
      "email": "xxxxxxxx@xxx.com",
      "passowrd": "xxxxxxxxx",
      "options":[
        "HomeAway.Disable"
      ]
  }
]

}

**Expected behavior**

Include with your bug report this version info:
```sh
node --version
homebridge --version
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
[8/7/2019, 4:09:04 PM] [Nest] Error: You did not specify your Nest app {'email','password'} in config.json
    at /usr/local/lib/node_modules/homebridge-nest/index.js:51:20
    at Promise._execute (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:79:10)
    at setupConnection (/usr/local/lib/node_modules/homebridge-nest/index.js:40:12)
    at NestPlatform.accessories (/usr/local/lib/node_modules/homebridge-nest/index.js:142:9)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:403:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:341:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11

**Comment by Johnyee1** [comment]
Similar to a previous posting, if I directly input the email and password to index.js it solves the problem. The plugin was able to ready "options" correctly though

**Comment by adriancable** [comment]
@Johnyee1 - your config.json contains a typo - you've written "passowrd" instead of "password".

Sorry but the plug-in doesn't yet include autocorrect! Will schedule that for version 4.

**Comment by Johnyee1** [comment]
Ahh, thanks for spotting that. That solves it.

And thanks for sharing this amazing plug-in!!
