### ISSUE TITLE
nest thermostats doesn't show

### ISSUE THREAD

**Issue by Shana611** [chrisjshull/homebridge-nest#128]
Hi after the new update my thermostats do not show on my homebridge & also Home app.
This error msg pop ups when the homebridge runs
  Error: You did not specify your Nest app {'email',                                                                                                                                                             'password'} in config.json
    at /usr/local/lib/node_modules/homebridge-nest/index.js:51:20
    at Promise._execute (/usr/local/lib/node_modules/homebridge-nest/node_module                                                                                                                                                             s/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/homebridge-nest                                                                                                                                                             /node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/usr/local/lib/node_modules/homebridge-nest/node_modules/blu                                                                                                                                                             ebird/js/release/promise.js:79:10)
    at setupConnection (/usr/local/lib/node_modules/homebridge-nest/index.js:40:                                                                                                                                                             12)
    at NestPlatform.accessories (/usr/local/lib/node_modules/homebridge-nest/ind                                                                                                                                                             ex.js:142:9)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/l                                                                                                                                                             ib/server.js:403:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.                                                                                                                                                             js:341:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge                                                                                                                                                             :17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by adriancable** [comment]
@Shana611 - please read the instructions in the README. You need to specify your Nest email and password in the config.json file, as the error message states.

If you still have problems, please post me your config.json file, with your password redacted. Thanks.

**Comment by Shana611** [comment]
Yes I did it but still have the same problem.

{
    "bridge": {
        "name": "Homebridge",
        "username": "EE:31:7E:F5:BF:50",
        "port": 51826,
        "pin": "081-85-184"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [],
    "platforms": [
        {
            "platform": "Nest",
            "usernam": "example@yahoo.com",
            "password": "1231475"
        },
        {

**Comment by Shana611** [comment]
Do I need to create new account & add thermostats again to the new account?

**Comment by markob100** [comment]
You have a typo in “usernam” (sic). Should be “username”. Might it just be that?

**Comment by Shana611** [comment]
I changed it to "username" but still same

**Comment by markob100** [comment]
Sorry, brain freeze. “email” not “username”. I’m just looking at the readme - it’s all there.

**Comment by Shana611** [comment]
Thank you so much **markob100**  that was the problem all sorted.
