### ISSUE TITLE
Redirect Errors.

### ISSUE THREAD

**Issue by hjdhjd** [chrisjshull/homebridge-nest#132]
I don't view this as a serious error, but I noticed them earlier today in poking through the logs for something else...

My guess is that it's some sort of administrative redirects from Google / Nest that happens on occasion? It's only shown up a couple of times...I presume it has to do with server availability on the Google end.

[Nest Platform] Nest_API_error StatusCodeError: 302 - "<html>redirect to <a href=\"https://czfe77-front01-iad01.transport.home.nest.com/v5/subscribe\">https://czfe77-front01-iad01.transport.home.nest.com/v5/subscrib
e</html>"
    at new StatusCodeError (/usr/local/lib/node_modules/homebridge-nest/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-nest/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-nest/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-nest/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at Gunzip.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  name: 'StatusCodeError',
  statusCode: 302,
  message: '302 - "<html>redirect to <a ' +
    'href=\\"https://czfe77-front01-iad01.transport.home.nest.com/v5/subscribe\\">https://czfe77-front01-iad01.transport.home.nest.com/v5/subscribe</html>"',
  error: '<html>redirect to <a ' +
    'href="https://czfe77-front01-iad01.transport.home.nest.com/v5/subscribe">https://czfe77-front01-iad01.transport.home.nest.com/v5/subscribe</html>',
  options: {
    method: 'POST',
    timeout: 60000,
    uri: 'https://czfe01-front01-iad01.transport.home.nest.com/v5/subscribe',
    headers: {
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) ' +
        'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 ' +
        'Safari/537.36',
      Authorization: 'Basic ' +
        'REDACTED',
      'X-nl-user-id': 'REDACTED',
      'X-nl-protocol-version': 1
    },
    body: { objects: [Array] },
    json: true,
    gzip: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },

**Comment by adriancable** [comment]
Ooh! That is a great spot. This is AWS load balancing issuing a redirect. Next release of homebridge-nest, I will fix so POST redirects are followed.

**Comment by adriancable** [comment]
Fixed in 3.3.0.
