### ISSUE TITLE
Home/away not working

### ISSUE THREAD

**Issue by leendersf** [chrisjshull/homebridge-nest#137]
**Describe the bug**
Homekit crashes when home/away gets switched to off with this error:
TypeError: Cannot read property 'startPropertyUpdate' of undefined
    at NestHomeAwayAccessory.setHome (/homebridge/node_modules/homebridge-nest/lib/nest-homeaway-accessory.js:56:21)
    at Characteristic.On.emit (events.js:189:13)
    at Characteristic.On.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:189:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**To Reproduce**
1. Switch the occupied home/away switch off (it is on when starting Homebridge)

**Expected behavior**
Homekit crashes.

Include with your bug report this version info:
`?`sh
node --version
homebridge --version
` 0.4.50`

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
@leendersf - I'm so sorry about this. This was a regression introduced when I refactored the event system in 3.3.0. It's now fixed - I have just published 3.3.2 on Github and npmjs. Please update and let me know how you get on. Thanks.

**Comment by leendersf** [comment]
It works like a charm! Thank you!
