### ISSUE TITLE
Possible to hide certain switches?

### ISSUE THREAD

**Issue by shred86** [chrisjshull/homebridge-nest#16]
It looks like I'm running this forked version of the homebridge-nest now, so that's good! Thanks again for continuing to update this plugin. However, I noticed now I have a few more "devices" listed in the Home app coming from my Nest thermostats. For example, in the past it was simply one device that allowed me to set the temperature. Now there is a switch for Eco mode, home occupancy switch and a fan. Is there any way to hide some of these from HomeKit?

**Comment by iogitio** [comment]
Curious if this is possible too, super cluttered in Home now :|

**Comment by chrisjshull** [comment]
It wouldn’t be that hard to disable these via config. But I wonder, does un-favoriting them in Home accomplish the same (or moving them to another Room)?

**Comment by shred86** [comment]
That's basically what I'm doing now (removing them from Statuses as well) but I'd prefer to disable them for a couple reasons:

1) Less clutter in the Home app. I use the Rooms views as well and prefer to only have items I intend to use making the experience easier and faster.

2) Less items for the Apple HomePod to get confused with. This just prevents triggering the wrong action. I run Home Bridge via Hassio (Home Assistant) and there's several switches I hide that I wouldn't want Siri to ever accidentally turn off or on such as a water valve.

**Comment by chrisjshull** [comment]
Well, certainly open to a PR. Probably won’t be able to get to this myself until next week at the earliest.

~Chris

**Comment by mriksman** [comment]
Yeah I've commented out these lines in nest-thermostat-accessory.js @ line 126;

```
//      var homeService = this.addService(Service.Switch, "Home Occupied", "home_occupied");
//      this.bindCharacteristic(homeService, Characteristic.On, "Home Occupied", this.getHome, this.setHome);

//      var thermostatEcoModeService = this.addService(Service.Switch, "Eco Mode", "eco_mode");
//      this.bindCharacteristic(thermostatEcoModeService, Characteristic.On, "Eco Mode", this.getEcoMode, this.setEcoMode);
```

**Comment by chrisjshull** [comment]
I just pushed a new version with a fix for this. You can now disable certain features by adding a setting like this to your config:
`"disable": ["Thermostat.Fan", "Thermostat.Home", "Thermostat.Eco"]`

To update to the latest version of homebridge-nest, simply run `npm update -g homebridge-nest`.

**Comment by iogitio** [comment]
Amazing, thanks for the quick update @chrisjshull ! appreciated!!!

**Comment by zyavrik** [comment]
Got this error:

```
[4/23/2023, 4:37:54 PM] There was a problem reading your config.json file.
[4/23/2023, 4:37:54 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[4/23/2023, 4:37:54 PM] 
SyntaxError: Unexpected token : in JSON at position 3595
    at JSON.parse (<anonymous>)
    at Function.loadConfig (/usr/local/lib/node_modules/homebridge/src/server.ts:228:21)
    at new Server (/usr/local/lib/node_modules/homebridge/src/server.ts:93:26)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:82:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
[4/23/2023, 4:37:54 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[4/23/2023, 4:37:59 PM] [HB Supervisor] Restarting Homebridge...
[4/23/2023, 4:37:59 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[4/23/2023, 4:37:59 PM] [HB Supervisor] Started Homebridge v1.6.0 with PID: 14102
[4/23/2023, 4:37:59 PM] There was a problem reading your config.json file.
[4/23/2023, 4:37:59 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[4/23/2023, 4:37:59 PM] 
SyntaxError: Unexpected token : in JSON at position 3595
    at JSON.parse (<anonymous>)
    at Function.loadConfig (/usr/local/lib/node_modules/homebridge/src/server.ts:228:21)
    at new Server (/usr/local/lib/node_modules/homebridge/src/server.ts:93:26)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:82:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

on

```
            "options": [
                "disable": ["Thermostat.Fan", "Thermostat.Home", "Thermostat.Eco"]
            ],
```

**Comment by zyavrik** [comment]
When I removed `"options"`, there was no error, but devices were not removed.

**Comment by adriancable** [comment]
Please post your whole config.json (you can redact the tokens). You are probably missing a comma somewhere.

**Comment by zyavrik** [comment]
Updated it according to the documentation https://github.com/chrisjshull/homebridge-nest#feature-options:

```
            "options": ["Thermostat.Fan.Disabled", "Thermostat.Home.Disabled", "Thermostat.Eco.Disabled"],
```

But it still failed to work after a restart.

**Comment by zyavrik** [comment]
No syntax error anymore. This is what I see in the UI for the last charing setting.

<img width="752" alt="Screenshot 2023-04-23 at 5 05 19 PM" src="https://user-images.githubusercontent.com/2708564/233874025-a91cb628-6864-4c46-9a5c-bc52337e4e90.png">

**Comment by zyavrik** [comment]
The full section for the plugin:

```
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "...",
                "cookies": "..."
            },
            "options": [
                "Thermostat.Fan.Disabled",
                "Thermostat.Home.Disabled",
                "Thermostat.Eco.Disabled"
            ],
            "platform": "Nest"
        }
```

**Comment by zyavrik** [comment]
The error was in `device` initially (must be `options`) and `Disabled` afterwards (must be `Disable`).
