### ISSUE TITLE
Unhandled Exception (500)

### ISSUE THREAD

**Issue by mrNakamura** [chrisjshull/homebridge-nest#174]
Hi
Everything's been working fine, then one morning got a 500 from Nest API (using Google account), after that Nest integration was broken until I restarted homebridge, then all ok.

[2019-11-11 09:35:06] [Nest] Retrying in 40 seconds.
[2019-11-11 09:36:25] [Nest] Nest API call to subscribe to device settings updates returned an error: 429
[2019-11-11 09:36:25] [Nest] Retrying in 40 seconds.
[2019-11-11 09:37:38] [Nest] Reauthenticating on Nest service ...
Unhandled rejection StatusCodeError: 500 - {"error":{"code":500,"message":"Internal error encountered.","status":"INTERNAL"}}
    at new StatusCodeError (/usr/lib/node_modules/homebridge-nest/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-nest/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-nest/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/lib/node_modules/homebridge-nest/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-nest/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-nest/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by adriancable** [comment]
500 is an error on the Nest side, not on your side. Sounds like all is OK now. Closing for now.

**Comment by mrNakamura** [comment]
Thanks Adrian - understood error on the Nest side, although it was the fact that once the 500 had occurred, things didn't recover until a manual restart of homebridge..

**Comment by adriancable** [comment]
Ah - got it. That shouldn't happen - will check into it.
