### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by Simon-Blades** [chrisjshull/homebridge-nest#186]
Hi,

I've created what I think is a correct config.json file however when running Homebridge on my RPi, I get the error below:

[12/8/2019, 9:10:03 AM] Error: The requested platform 'Nest' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[12/8/2019, 9:10:03 AM] Got SIGTERM, shutting down Homebridge...

Any idea why?

Thanks

**Comment by adriancable** [comment]
This looks like the Nest plug-in isn't being found by Homebridge. Do you know where the Nest plug-in got installed? It should be in the same place as Homebridge - so for example, if homebridge is in /usr/local/lib/node_modules/homebridge, the plug-in should be in /usr/local/lib/node_modules/homebridge-nest.

**Comment by Simon-Blades** [comment]
Thanks for your reply Adrian.

It was setup correctly and another member kindly got it working for me. 

I need to do some changes which allow it to automatically start in the event of a power cut and to also allow the setting of half degrees through the Home all (e.g. 17.5oC)

Thanks

**Comment by adriancable** [comment]
Unfortunately 0.5 degree C increments seem to be broken in iOS 13. See #169
