### ISSUE TITLE
Nest API call returning error on new setup

### ISSUE THREAD

**Issue by acahir** [chrisjshull/homebridge-nest#189]
Same error as reported in closed bug #157:

Error on startup:
Nest API call to subscribe to device settings updates returned an error: undefined then Retrying in 40 seconds. which then repeats.

I have not linked my Nest account with Google.

Also found [another reference to the same problem](https://techtechandmoretech.com/news/homebridge-setup/#comment-20564), but without a solution listed.

@Garywoo or @adriancable hoping you could share the resolution.

**Comment by acahir** [comment]
For reference in case anyone else encounters this problem. 

After some debugging, turns out that the plugin was encountering an error parsing the response for one device:

```
TypeError: Cannot read property 'mode' of undefined
    at /homebridge/node_modules/homebridge-nest/lib/nest-connection.js:386:56
    at Array.forEach (<anonymous>)
    at /homebridge/node_modules/homebridge-nest/lib/nest-connection.js:366:44
    at Array.forEach (<anonymous>)
    at apiResponseToObjectTree (/homebridge/node_modules/homebridge-nest/lib/nest-connection.js:354:29)
    at /homebridge/node_modules/homebridge-nest/lib/nest-connection.js:332:16
    at tryCatcher (/homebridge/node_modules/homebridge-nest/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/homebridge/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/homebridge/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/homebridge/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/homebridge/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/homebridge/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

One thermostat on my account was not returning an "eco" structure as part of the device record. The missing structure:

`"eco": {
                "mode": "schedule",
                "touched_by": 1,
                "mode_update_timestamp": 1569366808
            },`

This was probably missing because the thermostat is offline currently due to renovations, and its software version is trailing the other thermostats according to the API data returned.

The "Nest API call to subscribe to device settings updates returned an error: undefined" was just the next error block that was catching the error, that message was not the real cause.

Problem was solved by deleting the out-of-date thermostat from my nest account.
