### ISSUE TITLE
API observe: error Error: read ECONNRESET

### ISSUE THREAD

**Issue by Nastras** [chrisjshull/homebridge-nest#213]
Hello,
since the update to version 4.4.0 i have this error in the log after start homebridge. I have been using your plugin for quite some time and have never had any problems.

Do you have an idea what the problem is?

node is 12.16.1 LTS

![ED914C93-2983-442D-ACBF-E532F5C42837](https://user-images.githubusercontent.com/27686185/74901923-bb47ac80-53a4-11ea-8831-8bdd87f64e85.jpeg)
![6418B277-76E7-47A5-8D59-AE5B9132AF86](https://user-images.githubusercontent.com/27686185/74901928-bf73ca00-53a4-11ea-8309-6d7e97be51ff.jpeg)

Thanks for your efforts!

**Comment by adriancable** [comment]
@Nastras - looks like intermittent network connectivity issues. But I don't think there is much to worry about. The plug-in should reconnect as needed to keep the connection going.

**Comment by adriancable** [comment]
@Nastras - regarding the NGHTTP2_INTERNAL_ERROR, I need to see what is happening around that in more detail. Please can you edit your config.json, and under "platform": "Nest", insert:

"options": [ "Debug.Verbose" ],

Then run: homebridge -D

Then leave it running for a while, and after you get this error again, email me the complete output to: adrian.cable@gmail.com

Thanks!

**Comment by Nastras** [comment]
Hello and thank you very much for the quick reply.


> looks like intermittent network connectivity issues. But I don't think there is much to worry about. The plug-in should reconnect as needed to keep the connection going.

I observed it yesterday, the homebridge tried to reconnect after the bug but without success and stopped in the log at some point.

I have already switched on the DEBUG mode 😉 but without the changes in the Config.

Here another screen maybe it'll help a little?

![5CE70E7A-51A4-42AA-8A49-4B24E522AC4F](https://user-images.githubusercontent.com/27686185/74903748-2b0c6600-53aa-11ea-8409-70e88e751a87.jpeg)




I will now do it like you described it and send you a mail later.

**Comment by adriancable** [comment]
Nastra,
Thanks. Please can you remove the DEBUG flag (that enables HAP debugging - not useful to me) but add the "Debug.Verbose" flag as previously described and run: homebridge -D

Then, when this happens again email me the text output (not a screenshot) showing me what happens at least a minute before, and a minute after, you get the error. Thank you!

Also while we debug this, let's keep the conversation to email and then I will post a summary back to GitHub once we are done.

-Adrian

**Comment by Nastras** [comment]
> Also while we debug this, let's keep the conversation to email and then I will post a summary back to GitHub once we are done.

Yes, I will gladly do so as soon as the error occurs again.

> Please can you remove the DEBUG flag (that enables HAP debugging - not useful to me) but add the "Debug.Verbose" flag as previously described and run: homebridge -D

I don't quite understand. I should switch off the debug mode in the etc/default/homebridge-nest and only in the file var/homebridge-nest/config.json I should enter this here "options": [ "Debug.Verbose" ], and then record the log?


When I try to start the instance directly in the terminal with -D I get an error.

nastra@SHS:~ $ sudo systemctl restart homebridge-nest -D
systemctl: Ungültige Option -- D

**Comment by koupus** [comment]
Hello, same thing here since the last update.
An extract of the log:
![11D37482-0762-46C7-9671-E0D09C3EE0D6](https://user-images.githubusercontent.com/50924184/75010889-9b84b700-547e-11ea-8fda-b56b0606023c.jpeg)
Thanks for tour (great) work!
Tom

**Comment by adriancable** [comment]
@koupus - this looks basically normal except for the ECONNRESET which is probably from a brief network glitch, that is immediately recovered.

Again, nothing significant is wrong here. The 'context timed out' is not an error. Nest observe contexts last an hour, then they conclude and we start another one. As of what's now checked into Github, I will simply not display this info message because it is confusing people, making people think something is wrong when it is not.

-Adrian

**Comment by koupus** [comment]
@adriancable Thanks for your answer !

 And what do you think about it ? is it normal too ?

[2/22/2020, 10:05:12 AM] [Nest] API observe: error Error [ERR_HTTP2_STREAM_ERROR] [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR
    at ClientHttp2Stream._destroy (internal/http2/core.js:2159:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:55:8)
    at Http2Stream.onStreamClose (internal/http2/core.js:506:12)
 {
  code: 'ERR_HTTP2_STREAM_ERROR'
}

Thanks again, Tom

**Comment by adriancable** [comment]
@koupus - this is the mystery error I am trying to understand.

Please edit your config.json file, and under "platform": "Nest", add:

"options": [ "Debug.Verbose" ],

Then, if you run homebridge standalone, start it with: homebridge -D

If you run it via a service, then edit /etc/default/homebridge and to HOMEBRIDGE_OPTS add: -D

Then, when the error occurs again, please send me (adrian.cable@gmail.com) the log from a minute before the error occurs, to a minute after. Thanks!

**Comment by jojogrosso** [comment]
I am seeing the similar logs. Hope the below helps. If you want me to provide anything else, just let me know.

> [2/22/2020, 11:05:04 PM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/22/2020, 11:05:04 PM] [Nest] API observe: setting issue timer.
[2/22/2020, 11:25:25 PM] [Nest] Setting temperature to 17.2 °C / 63 °F
[2/22/2020, 11:29:57 PM] [Front Lock Dummy Switch] Setting switch to false
[2/23/2020, 12:05:04 AM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/23/2020, 12:05:04 AM] [Nest] API observe: setting issue timer.
[2/23/2020, 1:05:04 AM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/23/2020, 1:05:04 AM] [Nest] API observe: setting issue timer.
[2/23/2020, 2:05:04 AM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/23/2020, 2:05:04 AM] [Nest] API observe: setting issue timer.
[2/23/2020, 3:05:04 AM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/23/2020, 3:05:04 AM] [Nest] API observe: setting issue timer.
[2/23/2020, 4:05:05 AM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/23/2020, 4:05:05 AM] [Nest] API observe: setting issue timer.
[2/23/2020, 5:05:05 AM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/23/2020, 5:05:05 AM] [Nest] API observe: setting issue timer.
[2/23/2020, 6:05:05 AM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/23/2020, 6:05:05 AM] [Nest] API observe: setting issue timer.
[2/23/2020, 6:55:06 AM] [Nest] API observe: error Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
[2/23/2020, 6:55:06 AM] [Nest] Retrying in 10 seconds.
[2/23/2020, 6:55:16 AM] [Nest] API observe: setting issue timer.
[2/23/2020, 7:55:16 AM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/23/2020, 7:55:16 AM] [Nest] API observe: setting issue timer.

**Comment by koupus** [comment]
@adriancable Okay, il will try it...
I run homebridge has a service on a Mac and use the config UI X. Already edit my config.json file as you wish but don't find the /etc/default/homebridge and HOMEBRIDGE_OPTS.
Stil search...

**Comment by adriancable** [comment]
@jojogrosso - your log looks more or less normal.

@koupus - you need to find a way to run homebridge with the -D command line parameter. I am not familiar with running it on as a service on a Mac so I can't advise how to do that unfortunately.

**Comment by DJay-X** [comment]
Since a couple of days I also get error messages I didn't had before.
homebridge-nest v4.4.0
homebridge@0.4.50 | node@12.14.1 | npm 6.13.7

```
[2020-2-26 20:44:59] [Nest] API observe: setting issue timer.
[2020-2-26 21:34:40] [HomeConnect] Starting events stream for all appliances
[2020-2-26 21:45:00] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2020-2-26 21:45:00] [Nest] API observe: setting issue timer.
[2020-2-26 22:14:03] [Nest] API observe: error Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR
    at ClientHttp2Stream._destroy (internal/http2/core.js:2101:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8)
    at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2117:12)
    at Http2Stream.onStreamClose (internal/http2/core.js:493:26) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}
[2020-2-26 22:14:03] [Nest] Retrying in 10 seconds.
[2020-2-26 22:14:13] [Nest] API observe: setting issue timer.
[2020-2-26 22:20:56] [Nest] API observe: error Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR
    at ClientHttp2Stream._destroy (internal/http2/core.js:2101:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8)
    at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2117:12)
    at Http2Stream.onStreamClose (internal/http2/core.js:493:26) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}
[2020-2-26 22:20:56] [Nest] Retrying in 10 seconds.
[2020-2-26 22:21:06] [Nest] API observe: setting issue timer.
[2020-2-26 22:27:50] [Nest] API observe: error Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR
    at ClientHttp2Stream._destroy (internal/http2/core.js:2101:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8)
    at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2117:12)
    at Http2Stream.onStreamClose (internal/http2/core.js:493:26) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}
[2020-2-26 22:27:50] [Nest] Retrying in 10 seconds.
```

**Comment by roe1974** [comment]
same here ... :(

**Comment by adriancable** [comment]
@DJay-X & @roe1974 - to debug this, first edit config.json and underneath "platform": "Nest" add:

`"options": [ "Debug.Verbose" ],`

Then, assuming you are running homebridge standalone, run: `homebridge -D`

If you are running homebridge as a service, you will need to add `-D` to `HOMEBRIDGE_OPTS` in the service configuration file (which may be at /etc/default/homebridge or similar).

Then, when the ERR_HTTP2_STREAM_ERROR occurs, please email the log showing what happens from a minute before the error, to a minute after, to me at adrian.cable@gmail.com. Thanks!

**Comment by DJay-X** [comment]
Thanks a lot @adriancable . I appreciate your work and friendly support.
Unfortunately I can't provide a debug log in the next couple of days.
I will have an eye on the homebridge log after that and if still relevant, I will come back to you.
Thanks again.

**Comment by rogermeijer** [comment]
> Again, nothing significant is wrong here. The 'context timed out' is not an error. Nest observe contexts last an hour, then they conclude and we start another one. As of what's now checked into Github, I will simply not display this info message because it is confusing people, making people think something is wrong when it is not.

@adriancable, are you saying you are going to remove the log tracking of the messages below from the application? In other words, they are normal behavior? I would indeed advise to remove them :)

`[27/02/2020, 13:34:21] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[27/02/2020, 13:34:21] [Nest] API observe: setting issue timer.
[27/02/2020, 14:34:22] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[27/02/2020, 14:34:22] [Nest] API observe: setting issue timer.
[27/02/2020, 15:34:22] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[27/02/2020, 15:34:22] [Nest] API observe: setting issue timer.
[27/02/2020, 16:34:23] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[27/02/2020, 16:34:23] [Nest] API observe: setting issue timer.
[27/02/2020, 17:34:23] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[27/02/2020, 17:34:23] [Nest] API observe: setting issue timer.
[27/02/2020, 18:34:24] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[27/02/2020, 18:34:24] [Nest] API observe: setting issue timer.`

Thanks for this great application!

**Comment by adriancable** [comment]
@rogermeijer - yes, these are normal, and they have already been removed from the latest commit on Github. npmjs is sometimes behind the latest commit on github though.

**Comment by roe1974** [comment]
@adriancable 
I have an other error .... like:

Feb 28 01:06:20 homebridge-raspi homebridge[21104]: [2/28/2020, 01:06:20] [Nest] API observe: error Error: read ECONNRESET
Feb 28 01:06:20 homebridge-raspi homebridge[21104]:     at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {
Feb 28 01:06:20 homebridge-raspi homebridge[21104]:   errno: 'ECONNRESET',
Feb 28 01:06:20 homebridge-raspi homebridge[21104]:   code: 'ECONNRESET',
Feb 28 01:06:20 homebridge-raspi homebridge[21104]:   syscall: 'read'
Feb 28 01:06:20 homebridge-raspi homebridge[21104]: }

do you therefore also need logs in debug mode ?

Richard

**Comment by jojogrosso** [comment]
I'm not sure if this relates to this thread, but seems like after the update I wasn't able to update the Nest Thermostat through HomeKit. I ended up having to re-do the issueToken, Cookie, and API. Now it seems to be working (changing temps, etc), but I get the following in Homebridge. Should I have to do anything to correct the below?

> [2/28/2020, 11:59:53 PM] Homebridge is running on port 51673.
[2/29/2020, 12:59:53 AM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/29/2020, 12:59:53 AM] [Nest] API observe: setting issue timer.
[2/29/2020, 1:59:53 AM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/29/2020, 1:59:53 AM] [Nest] API observe: setting issue timer.
[2/29/2020, 2:59:53 AM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/29/2020, 2:59:53 AM] [Nest] API observe: setting issue timer.
[2/29/2020, 3:59:53 AM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/29/2020, 3:59:53 AM] [Nest] API observe: setting issue timer.
[2/29/2020, 4:59:53 AM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/29/2020, 4:59:53 AM] [Nest] API observe: setting issue timer.
[2/29/2020, 5:44:29 AM] [Nest] Setting temperature to 18.9 °C / 66 °F
[2/29/2020, 5:59:54 AM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/29/2020, 5:59:54 AM] [Nest] API observe: setting issue timer.
[2/29/2020, 6:13:30 AM] [Nest] Setting temperature to 16.7 °C / 62 °F
[2/29/2020, 6:59:54 AM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/29/2020, 6:59:54 AM] [Nest] API observe: setting issue timer.
[2/29/2020, 7:29:08 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 7:29:08 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 7:29:37 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 7:29:37 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 7:30:06 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 7:30:06 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 7:38:34 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 7:38:34 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 7:43:03 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 7:43:03 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 7:43:33 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 7:43:33 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 7:44:02 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 7:44:02 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 7:44:31 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 7:44:31 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 7:45:00 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 7:45:00 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 7:47:30 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 7:47:30 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 7:47:59 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 7:47:59 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 7:50:28 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 7:50:28 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 7:50:58 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 7:50:58 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 7:57:27 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 7:57:27 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 7:59:54 AM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }
[2/29/2020, 7:59:54 AM] [Nest] API observe: setting issue timer.
[2/29/2020, 8:03:57 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 8:03:57 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 8:04:26 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 8:04:26 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 8:08:56 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 8:08:56 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 8:09:25 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 8:09:25 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 8:09:54 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 8:09:54 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 8:11:09 AM] [Nest] Setting temperature to 18.9 °C / 66 °F
[2/29/2020, 8:11:28 AM] [Nest] Setting temperature to 18.9 °C / 66 °F
[2/29/2020, 8:11:30 AM] [Nest] Nest API call to change device settings returned an error: ECONNRESET
[2/29/2020, 8:11:51 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 8:11:51 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 8:12:15 AM] [Nest] Setting temperature to 20 °C / 68 °F
[2/29/2020, 8:12:20 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 8:12:20 AM] [Nest] Retrying in 10 seconds.
[2/29/2020, 8:12:49 AM] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[2/29/2020, 8:12:49 AM] [Nest] Retrying in 10 seconds.

**Comment by Nastras** [comment]
> @rogermeijer - yes, these are normal, and they have already been removed from the latest commit on Github. npmjs is sometimes behind the latest commit on github though.


Hello @adriancable 
i would like to use the change but i can't find the change under commit can you link it?


Thank You!

**Comment by Nastras** [comment]
I don't get the error and the message with the new version anymore so I close the issue now.

@adriancable Thanks!

**Comment by imgleb** [comment]
dont run a vpn and you wont have ECONNREST issues
