### ISSUE TITLE
Unhandled Rejection Status when loading homebridge Nest plugin. Haven't changed anything to Config.json

### ISSUE THREAD

**Issue by lucanaut** [chrisjshull/homebridge-nest#236]
I noticed a couple of days ago that my nest devices were no longer showing up in the home app, so I pulled up homebridge and noticed that there was a lengthy failure message at startup.  I haven't changed anything on my config file.  Just in case I went through the process once again of setting up the config file with the proper values but I am still getting the message.  The other plug ins are working.  I am not even quite sure what's failing?  Anyone else experiencing this? 

Unhandled rejection StatusCodeError: 404 - "<!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\"><title>Error 404 (Not Found)!!1</title><style nonce=\"FJI5Bmg8jCqgxSS2SsI2yw\">*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{color:#222;text-align:unset;margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px;}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}pre{white-space:pre-wrap;}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><div id=\"af-error-container\"><a href=//www.google.com><span id=logo aria-label=Google></span></a><p><b>404.</b> <ins>That’s an error.</ins><p>The The requested URL was not found on this server. <ins>That’s all we know.</ins></div>"
    at new StatusCodeError (/usr/local/lib/node_modules/homebridge-nest/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-nest/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-nest/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-nest/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/request/request.js:1161:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by adriancable** [comment]
@lucanaut - that is super weird. Please can you tell me more about your setup, i.e. your node version, and plug-in version.

Then please can you email me your config.json to adrian.cable@gmail.com - please scramble a few of the cookies/tokens to invalidate them (e.g. replace some of the letters). Then, in your config.json, under "platform": "Nest", add:

"options": [ "Debug.Verbose "],

Then run: homebridge -D

Then email me the **complete** output of homebridge showing the error message, and the surrounding context. Thank you!
