### ISSUE TITLE
Upgraded and now getting an error

### ISSUE THREAD

**Issue by fullphat** [chrisjshull/homebridge-nest#239]
**Describe the bug**

Upgraded to latest version of the plugin and now getting the following on boot:

```
[4/21/2020, 20:05:46] ====================
[4/21/2020, 20:05:46] ERROR LOADING PLUGIN homebridge-nest:
[4/21/2020, 20:05:46] ReferenceError: b5 is not defined
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-nest/node_modules/object-keys/isArguments.js:1:2)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-nest/node_modules/object-keys/index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
[4/21/2020, 20:05:46] ====================
```

**To Reproduce**
1.  Launch Homebridge

**Expected behavior**

Homebridge should just start :-)

Include with your bug report this version info:
```sh
node --version

v12.16.2

homebridge --version

0.4.53

```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
@fullphat - it looks like something in your node_modules got corrupted. Can you send me your /usr/lib/node_modules/homebridge-nest/node_modules/object-keys/isArguments.js file?

You might also want to try clearing homebridge-nest/node-modules/* and then running npm i.

**Comment by fullphat** [comment]
Here you go, I did take a look and it doesn't look quite right, but I have no idea what I'm looking at either! :D

```
b5;
  t14 += v * b6;
  t15 += v * b7;
  t16 += v * b8;
  t17 += v * b9;
  t18 += v * b10;
  t19 += v * b11;
  t20 += v * b12;
  t21 += v * b13;
  t22 += v * b14;
  t23 += v * b15;
  v = a[9];
  t9 += v * b0;
  t10 += v * b1;
  t11 += v * b2;
  t12 += v * b3;
  t13 += v * b4;
  t14 += v * b5;
  t15 += v * b6;
  t16 += v * b7;
  t17 += v * b8;
  t18 += v * b9;
  t19 += v * b10;
  t20 += v * b11;
  t21 += v * b12;
  t22

```

**Comment by fullphat** [comment]
> clearing homebridge-nest/node-modules/* and then running npm i.

This fixed it!

**Comment by adriancable** [comment]
@fullphat - looks like your node_modules got corrupted - that looks like something from an ed25519 elliptic curve module, definitely not related to object-keys. Maybe SSD corruption? Anyway - happy it's now working!
