### ISSUE TITLE
SyntaxError on config.json

### ISSUE THREAD

**Issue by fichmann** [chrisjshull/homebridge-nest#240]
Not sure why Im getting the error after configuring config.json according to the template provided.

/usr/lib/node_modules/homebridge/lib/server.js:218
    throw err;
    ^

SyntaxError: Unexpected token : in JSON at position 10
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:212:19)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:56:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:32:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by fichmann** [comment]
File is:


"platforms": [
        {
                "platform": "Nest",
                "googleAuth": {
                  "issueToken": "https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response...",
                  "cookies": "SMSV=ADHTe-By...",
                  "apiKey": "AIzaSyA...."
                }
        }
],

**Comment by fichmann** [comment]
missed a { in the begining and end.
