### ISSUE TITLE
Seeing devices in logs, but not showing up in ios

### ISSUE THREAD

**Issue by pmeisel123** [chrisjshull/homebridge-nest#258]
**Describe the bug**

I am not getting my thermostats to show up in the home app, though I do see other accessories showing up from this bridge.

I do see in the homebridge logs
[5/27/2020, 06:42:58] [Nest] initing thermostat "Upstairs Thermostat": deviceId: XXXXXX
[5/27/2020, 06:42:59] [Nest] initing thermostat "Downstairs Thermostat": deviceId:  XXXX
[5/27/2020, 06:42:59] [Nest] initing home_away_sensor "Home Occupied": deviceId: XXXXX

So, it authenticating.

I see this from the errors:

> 2020-05-27T10:49:41.679Z follow-redirects options {
>   protocol: 'https:',
>   maxRedirects: 21,
>   maxBodyLength: 10485760,
>   path: '/v5/subscribe',
>   method: 'POST',
>   headers: {
>     Accept: 'application/json, text/plain, */*',
>     'Content-Type': 'application/json;charset=utf-8',
>     'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36',
>     Authorization: 'Basic XXXXXX',
>     'X-nl-user-id': 'XXXXXX'
>     'X-nl-protocol-version': 1,
>     'Content-Length': 1140
>   },
>   agent: undefined,
>   agents: { http: undefined, https: undefined },
>   auth: undefined,
>   hostname: 'czfe101-front01-iad01.transport.home.nest.com',
>   port: null,
>   nativeProtocols: {
>     'http:': {
>       _connectionListener: [Function: connectionListener],
>       METHODS: [Array],
>       STATUS_CODES: [Object],
>       Agent: [Function],
>       ClientRequest: [Function: ClientRequest],
>       IncomingMessage: [Function: IncomingMessage],
>       OutgoingMessage: [Function: OutgoingMessage],
>       Server: [Function: Server],
>       ServerResponse: [Function: ServerResponse],
>       createServer: [Function: createServer],
>       get: [Function: get],
>       request: [Function: request],
>       maxHeaderSize: [Getter],
>       globalAgent: [Getter/Setter]
>     },
>     'https:': {
>       Agent: [Function: Agent],
>       globalAgent: [Agent],
>       Server: [Function: Server],
>       createServer: [Function: createServer],
>       get: [Function: get],
>       request: [Function: request]
>     }
>   }
> }
> [5/27/2020, 06:49:44] Error: listen EADDRINUSE: address already in use :::51822
>     at Server.setupListenHandle [as _listen2] (net.js:1313:16)
>     at listenInCluster (net.js:1361:12)
>     at Server.listen (net.js:1447:7)
>     at EventedHTTPServer._this.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:85:21)
>     at HAPServer._this.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:236:22)
>     at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:974:18)
>     at Server.publishBridge (/usr/local/lib/node_modules/homebridge/src/server.ts:191:17)
>     at /usr/local/lib/node_modules/homebridge/src/server.ts:163:24
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:162:5)
> 

**Additional**
It was working when I was using the developer portal method.  But I just had to wipe and reinstall npm and all the modules.  I changed my config to use the new method

**To Reproduce**
No clue...

**Expected behavior**

Include with your bug report this version info:
```sh
node --version
homebridge --version
```
v12.17.0
1.1.0

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

[5/27/2020, 06:57:44] [Nest] Authentication successful.
[5/27/2020, 06:57:45] [Nest] initing thermostat "Upstairs Thermostat": deviceId: XXXXX
[5/27/2020, 06:57:45] [Nest] Temperature unit for Upstairs Thermostat is: Fahrenheit
[5/27/2020, 06:57:45] [Nest] Current temperature for Upstairs Thermostat is: 19.79999 °C / 67.5 °F
[5/27/2020, 06:57:45] [Nest] Current humidity for Upstairs Thermostat is: 47%
[5/27/2020, 06:57:45] [Nest] Target temperature for Upstairs Thermostat is: 19.97627 °C / 68 °F
[5/27/2020, 06:57:45] [Nest] Target heating/cooling state for Upstairs Thermostat is: Cool
[5/27/2020, 06:57:45] [Nest] Cooling threshold temperature for Upstairs Thermostat is: 24.444444444444443 °C / 76 °F
[5/27/2020, 06:57:45] [Nest] Heating threshold temperature for Upstairs Thermostat is: 14.44443 °C / 58 °F
[5/27/2020, 06:57:45] [Nest] Online status for Upstairs Thermostat is: true
[5/27/2020, 06:57:45] [Nest] Fan Timer Duration for Upstairs Thermostat is: 60
[5/27/2020, 06:57:45] [Nest] initing thermostat "Downstairs Thermostat": deviceId: XXXXX
[5/27/2020, 06:57:45] [Nest] Temperature unit for Downstairs Thermostat is: Fahrenheit
[5/27/2020, 06:57:45] [Nest] Current temperature for Downstairs Thermostat is: 20.25999 °C / 68.5 °F
[5/27/2020, 06:57:45] [Nest] Current humidity for Downstairs Thermostat is: 44%
[5/27/2020, 06:57:45] [Nest] Target temperature for Downstairs Thermostat is: 21.11111111111111 °C / 70 °F
[5/27/2020, 06:57:45] [Nest] Target heating/cooling state for Downstairs Thermostat is: Cool
[5/27/2020, 06:57:45] [Nest] Cooling threshold temperature for Downstairs Thermostat is: 24 °C / 75 °F
[5/27/2020, 06:57:45] [Nest] Heating threshold temperature for Downstairs Thermostat is: 20 °C / 68 °F
[5/27/2020, 06:57:45] [Nest] Online status for Downstairs Thermostat is: true
[5/27/2020, 06:57:45] [Nest] Fan Timer Duration for Downstairs Thermostat is: 60
[5/27/2020, 06:57:45] [Nest] Sunlight Correction Enabled for Downstairs Thermostat is: true
[5/27/2020, 06:57:45] [Nest] initing home_away_sensor "Home Occupied": deviceId: XXXXXXX
[5/27/2020, 06:57:45] [Nest] Home Occupied for Home Occupied is: true
[5/27/2020, 06:57:45] Initializing platform accessory 'Upstairs Thermostat'...
[5/27/2020, 06:57:45] Initializing platform accessory 'Downstairs Thermostat'...
[5/27/2020, 06:57:45] Initializing platform accessory 'Home Occupied'...

**Comment by pmeisel123** [comment]
Apparently removing the bridge from my phone, and renaming the username of the bridge was not enough.

I rebooted the pi and removing the bridge from ios, and then renamed the username, and that fixed the problem.
