### ISSUE TITLE
Nest devices not showing up

### ISSUE THREAD

**Issue by joetlawson** [chrisjshull/homebridge-nest#315]
**Describe the bug**

**To Reproduce**
1. Installed plugin and configured Issue token cookies and API

**Expected behavior**
Nest thermostat and protects as well as locks to show up
Include with your bug report this version info:
```sh
node --version
homebridge --version
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

I have the Nest cam plugin installed as well and configured with the same info and it works minus the API key

**Comment by adriancable** [comment]
@joetlawson - I'm here to help but there is almost no information at all in your post so there's nowhere to start. Can you please at least begin by sending the log output from Homebridge start-up? Thanks.

**Comment by joetlawson** [comment]
See below apologies I was at work when I posted this and got busy right at the time I started to post.



Preparing to unpack .../147-libxv1_2%3a1.0.11-1_amd64.deb ...
Unpacking libxv1:amd64 (2:1.0.11-1) ...
Selecting previously unselected package libavdevice58:amd64.
Preparing to unpack .../148-libavdevice58_7%3a4.1.4-1build2_amd64.deb ...
Unpacking libavdevice58:amd64 (7:4.1.4-1build2) ...
Selecting previously unselected package libavresample4:amd64.
Preparing to unpack .../149-libavresample4_7%3a4.1.4-1build2_amd64.deb ...
Unpacking libavresample4:amd64 (7:4.1.4-1build2) ...
Selecting previously unselected package ffmpeg.
Preparing to unpack .../150-ffmpeg_7%3a4.1.4-1build2_amd64.deb ...
Unpacking ffmpeg (7:4.1.4-1build2) ...
Selecting previously unselected package libigdgmm11:amd64.
Preparing to unpack .../151-libigdgmm11_19.3.2+ds1-0ubuntu2_amd64.deb ...
Unpacking libigdgmm11:amd64 (19.3.2+ds1-0ubuntu2) ...
Selecting previously unselected package intel-media-va-driver:amd64.

Preparing to unpack .../152-intel-media-va-driver_19.2.1+dfsg1-2ubuntu1_amd64.deb ...
Unpacking intel-media-va-driver:amd64 (19.2.1+dfsg1-2ubuntu1) ...

Selecting previously unselected package libaacs0:amd64.
Preparing to unpack .../153-libaacs0_0.9.0-2_amd64.deb ...
Unpacking libaacs0:amd64 (0.9.0-2) ...
Selecting previously unselected package libbdplus0:amd64.
Preparing to unpack .../154-libbdplus0_0.1.2-3_amd64.deb ...
Unpacking libbdplus0:amd64 (0.1.2-3) ...
Selecting previously unselected package libgdk-pixbuf2.0-bin.
Preparing to unpack .../155-libgdk-pixbuf2.0-bin_2.40.0+dfsg-1build1_amd64.deb ...
Unpacking libgdk-pixbuf2.0-bin (2.40.0+dfsg-1build1) ...
Selecting previously unselected package librsvg2-common:amd64.
Preparing to unpack .../156-librsvg2-common_2.44.14-1_amd64.deb ...
Unpacking librsvg2-common:amd64 (2.44.14-1) ...
Selecting previously unselected package mesa-va-drivers:amd64.
Preparing to unpack .../157-mesa-va-drivers_19.2.8-0ubuntu0~19.10.3_amd64.deb ...
Unpacking mesa-va-drivers:amd64 (19.2.8-0ubuntu0~19.10.3) ...
Selecting previously unselected package mesa-vdpau-drivers:amd64.
Preparing to unpack .../158-mesa-vdpau-drivers_19.2.8-0ubuntu0~19.10.3_amd64.deb ...
Unpacking mesa-vdpau-drivers:amd64 (19.2.8-0ubuntu0~19.10.3) ...
Selecting previously unselected package i965-va-driver:amd64.

Preparing to unpack .../159-i965-va-driver_2.3.0-0ubuntu2_amd64.deb ...
Unpacking i965-va-driver:amd64 (2.3.0-0ubuntu2) ...

Selecting previously unselected package va-driver-all:amd64.

Preparing to unpack .../160-va-driver-all_2.5.0-1_amd64.deb ...

Unpacking va-driver-all:amd64 (2.5.0-1) ...

Selecting previously unselected package vdpau-driver-all:amd64.

Preparing to unpack .../161-vdpau-driver-all_1.2-1ubuntu1_amd64.deb ...

Unpacking vdpau-driver-all:amd64 (1.2-1ubuntu1) ...

Setting up libgme0:amd64 (0.6.2-1) ...
Setting up libssh-gcrypt-4:amd64 (0.9.0-1ubuntu1.4) ...
Setting up libgraphite2-3:amd64 (1.3.13-8) ...
Setting up libxcb-dri3-0:amd64 (1.13.1-2) ...
Setting up libpixman-1-0:amd64 (0.38.4-0ubuntu1) ...
Setting up libx11-xcb1:amd64 (2:1.6.8-1) ...
Setting up libpciaccess0:amd64 (0.16-0ubuntu1) ...
Setting up libraw1394-11:amd64 (2.1.2-1) ...
Setting up libsodium23:amd64 (1.0.18-1) ...
Setting up libxdamage1:amd64 (1:1.1.5-1) ...
Setting up libmpg123-0:amd64 (1.25.12-1build1) ...
Setting up libxcb-xfixes0:amd64 (1.13.1-2) ...
Setting up libogg0:amd64 (1.3.4-0ubuntu1) ...
Setting up libspeex1:amd64 (1.2~rc1.2-1ubuntu2) ...
Setting up libshine3:amd64 (3.1.1-2) ...
Setting up libcaca0:amd64 (0.99.beta19-2.1) ...
Setting up libxi6:amd64 (2:1.7.10-0ubuntu1) ...
Setting up libtwolame0:amd64 (0.3.13-4) ...
Setting up libxrender1:amd64 (1:0.9.10-1) ...
Setting up libdatrie1:amd64 (0.2.12-3) ...
Setting up libgsm1:amd64 (1.0.18-2) ...
Setting up libx264-155:amd64 (2:0.155.2917+git0a84d98-2) ...
Setting up libxcb-render0:amd64 (1.13.1-2) ...
Setting up libsoxr0:amd64 (0.1.3-1) ...
Setting up libglvnd0:amd64 (1.1.1-0ubuntu1) ...
Setting up libxcb-glx0:amd64 (1.13.1-2) ...
Setting up libaom0:amd64 (1.0.0-3) ...
Setting up libgdk-pixbuf2.0-common (2.40.0+dfsg-1build1) ...
Setting up libcodec2-0.8.1:amd64 (0.8.1-2) ...
Setting up libnorm1:amd64 (1.5.8+dfsg2-2) ...
Setting up libxcb-shape0:amd64 (1.13.1-2) ...
Setting up x11-common (1:7.7+19ubuntu12) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults

invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up libsensors-config (1:3.5.0-3ubuntu1) ...
Setting up libcdio18:amd64 (2.0.0-2) ...
Setting up xkb-data (2.26-2ubuntu2) ...
Setting up libmysofa0:amd64 (0.7~dfsg0-1) ...
Setting up libxcb-shm0:amd64 (1.13.1-2) ...
Setting up libxvidcore4:amd64 (2:1.3.5-1) ...
Setting up libjbig0:amd64 (2.1-3.1build1) ...
Setting up libxxf86vm1:amd64 (1:1.1.4-1build1) ...
Setting up libsnappy1v5:amd64 (1.1.7-1) ...
Setting up libflac8:amd64 (1.3.3-1) ...
Setting up libxcb-present0:amd64 (1.13.1-2) ...
Setting up libasound2-data (1.1.9-0ubuntu1.3) ...
Setting up libva2:amd64 (2.5.0-1) ...
Setting up libwrap0:amd64 (7.6.q-28build1) ...
Setting up libigdgmm11:amd64 (19.3.2+ds1-0ubuntu2) ...
Setting up libxfixes3:amd64 (1:5.0.3-1) ...
Setting up libxcb-sync1:amd64 (1.13.1-2) ...
Setting up libfribidi0:amd64 (1.0.5-3.1ubuntu0.19.10.1) ...
Setting up libopus0:amd64 (1.3.1-0ubuntu1) ...
Setting up libxinerama1:amd64 (2:1.1.4-2) ...
Setting up intel-media-va-driver:amd64 (19.2.1+dfsg1-2ubuntu1) ...

Setting up libxv1:amd64 (2:1.0.11-1) ...
Setting up libpng16-16:amd64 (1.6.37-1) ...
Setting up libvorbis0a:amd64 (1.3.6-2) ...
Setting up libxrandr2:amd64 (2:1.5.2-0ubuntu1) ...
Setting up libwebp6:amd64 (0.6.1-2) ...
Setting up libcroco3:amd64 (0.6.13-1) ...
Setting up fonts-dejavu-core (2.37-1) ...
Setting up libsensors5:amd64 (1:3.5.0-3ubuntu1) ...
Setting up libaacs0:amd64 (0.9.0-2) ...
Setting up libjpeg-turbo8:amd64 (2.0.3-0ubuntu1.19.10.1) ...
Setting up libfftw3-double3:amd64 (3.3.8-2) ...
Setting up libglapi-mesa:amd64 (19.2.8-0ubuntu0~19.10.3) ...
Setting up libxcb-dri2-0:amd64 (1.13.1-2) ...
Setting up libbdplus0:amd64 (0.1.2-3) ...
Setting up libnuma1:amd64 (2.0.12-1) ...
Setting up libvidstab1.1:amd64 (1.1.0-2) ...
Setting up libx265-176:amd64 (3.1.1-2) ...
Setting up libasyncns0:amd64 (0.8-6) ...
Setting up libxshmfence1:amd64 (1.3-1) ...
Setting up libvpx6:amd64 (1.8.1-2) ...
Setting up libvdpau1:amd64 (1.2-1ubuntu1) ...
Setting up libwavpack1:amd64 (5.1.0-7) ...
Setting up libbs2b0:amd64 (3.1.0+dfsg-2.2) ...
Setting up libasound2:amd64 (1.1.9-0ubuntu1.3) ...
Setting up libopenjp2-7:amd64 (2.3.0-2build0.19.10.1) ...
Setting up libopenal-data (1:1.19.1-1) ...
Setting up libthai-data (0.1.28-3) ...
Setting up libwayland-egl1:amd64 (1.17.0-1) ...
Setting up libxss1:amd64 (1:1.2.3-1) ...
Setting up libusb-1.0-0:amd64 (2:1.0.23-1) ...
Setting up libsamplerate0:amd64 (0.1.9-2) ...
Setting up libwebpmux3:amd64 (0.6.1-2) ...
Setting up libdrm-common (2.4.99-1ubuntu1) ...
Setting up libllvm9:amd64 (1:9-2) ...
Setting up libzvbi-common (0.2.35-16) ...
Setting up libmp3lame0:amd64 (3.100-2build1) ...
Setting up libvorbisenc2:amd64 (1.3.6-2) ...
Setting up libpgm-5.2-0:amd64 (5.2.122~dfsg-3) ...
Setting up libiec61883-0:amd64 (1.2.0-3) ...
Setting up libserd-0-0:amd64 (0.28.0~dfsg0-1) ...
Setting up libxkbcommon0:amd64 (0.8.4-1) ...
Setting up libwayland-client0:amd64 (1.17.0-1) ...
Setting up libjpeg8:amd64 (8c-2ubuntu8) ...
Setting up libavc1394-0:amd64 (0.5.4-5) ...
Setting up libzvbi0:amd64 (0.2.35-16) ...
Setting up libzmq5:amd64 (4.3.2-1) ...
Setting up libcdio-cdda2:amd64 (10.2+2.0.0-1) ...
Setting up fontconfig-config (2.13.1-2ubuntu2) ...
Setting up libcdio-paranoia2:amd64 (10.2+2.0.0-1) ...
Setting up libxcursor1:amd64 (1:1.2.0-2) ...
Setting up libdc1394-22:amd64 (2.2.5-2) ...
Setting up libthai0:amd64 (0.1.28-3) ...
Setting up libvorbisfile3:amd64 (1.3.6-2) ...
Setting up libfreetype6:amd64 (2.9.1-4) ...
Setting up librubberband2:amd64 (1.8.1-7ubuntu2) ...
Setting up libsndio7.0:amd64 (1.5.0-3) ...
Setting up libjack-jackd2-0:amd64 (1.9.12~dfsg-2build1) ...
Setting up libdrm2:amd64 (2.4.99-1ubuntu1) ...
Setting up libflite1:amd64 (2.1-release-3) ...
Setting up libva-drm2:amd64 (2.5.0-1) ...
Setting up libsord-0-0:amd64 (0.16.0~dfsg0-1) ...
Setting up libwayland-cursor0:amd64 (1.17.0-1) ...
Setting up libsratom-0-0:amd64 (0.6.0~dfsg0-1) ...
Setting up libharfbuzz0b:amd64 (2.6.1-3) ...
Setting up libtiff5:amd64 (4.0.10+git191003-1) ...
Setting up libfontconfig1:amd64 (2.13.1-2ubuntu2) ...
Setting up libsndfile1:amd64 (1.0.28-6) ...
Setting up libbluray2:amd64 (1:1.1.2-2) ...
Setting up libva-x11-2:amd64 (2.5.0-1) ...
Setting up liblilv-0-0:amd64 (0.24.4~dfsg0-1) ...
Setting up libopenmpt0:amd64 (0.4.6-1) ...
Setting up libdrm-amdgpu1:amd64 (2.4.99-1ubuntu1) ...
Setting up fontconfig (2.13.1-2ubuntu2) ...
Regenerating fonts cache... done.
Setting up libdrm-nouveau2:amd64 (2.4.99-1ubuntu1) ...
Setting up libpulse0:amd64 (1:13.0-1ubuntu1.2) ...
Setting up libdrm-radeon1:amd64 (2.4.99-1ubuntu1) ...
Setting up libpango-1.0-0:amd64 (1.42.4-7) ...
Setting up libdrm-intel1:amd64 (2.4.99-1ubuntu1) ...
Setting up libgl1-mesa-dri:amd64 (19.2.8-0ubuntu0~19.10.3) ...
Setting up libopenal1:amd64 (1:1.19.1-1) ...
Setting up libcairo2:amd64 (1.16.0-4) ...
Setting up libavutil56:amd64 (7:4.1.4-1build2) ...
Setting up libass9:amd64 (1:0.14.0-2) ...
Setting up libgdk-pixbuf2.0-0:amd64 (2.40.0+dfsg-1build1) ...
Setting up libpostproc55:amd64 (7:4.1.4-1build2) ...
Setting up libgdk-pixbuf2.0-bin (2.40.0+dfsg-1build1) ...
Setting up libtheora0:amd64 (1.1.1+dfsg.1-15) ...
Setting up libswscale5:amd64 (7:4.1.4-1build2) ...
Setting up mesa-va-drivers:amd64 (19.2.8-0ubuntu0~19.10.3) ...
Setting up libpangoft2-1.0-0:amd64 (1.42.4-7) ...
Setting up libsdl2-2.0-0:amd64 (2.0.10+dfsg1-1ubuntu1) ...
Setting up i965-va-driver:amd64 (2.3.0-0ubuntu2) ...

Setting up libpangocairo-1.0-0:amd64 (1.42.4-7) ...
Setting up mesa-vdpau-drivers:amd64 (19.2.8-0ubuntu0~19.10.3) ...
Setting up libglx-mesa0:amd64 (19.2.8-0ubuntu0~19.10.3) ...
Setting up libglx0:amd64 (1.1.1-0ubuntu1) ...
Setting up libswresample3:amd64 (7:4.1.4-1build2) ...
Setting up libavresample4:amd64 (7:4.1.4-1build2) ...
Setting up librsvg2-2:amd64 (2.44.14-1) ...
Setting up libgl1:amd64 (1.1.1-0ubuntu1) ...
Setting up va-driver-all:amd64 (2.5.0-1) ...

Setting up librsvg2-common:amd64 (2.44.14-1) ...
Setting up vdpau-driver-all:amd64 (1.2-1ubuntu1) ...

Setting up libavcodec58:amd64 (7:4.1.4-1build2) ...
Setting up libchromaprint1:amd64 (1.4.3-3) ...
Setting up libavformat58:amd64 (7:4.1.4-1build2) ...
Setting up libavfilter7:amd64 (7:4.1.4-1build2) ...
Setting up libavdevice58:amd64 (7:4.1.4-1build2) ...
Setting up ffmpeg (7:4.1.4-1build2) ...
Processing triggers for systemd (242-7ubuntu3.6) ...
Processing triggers for libc-bin (2.30-0ubuntu2) ...
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.40.0+dfsg-1build1) ...

> bufferutil@4.0.1 install /usr/lib/node_modules/homebridge-pilight/node_modules/bufferutil
> node-gyp-build


> utf-8-validate@5.0.2 install /usr/lib/node_modules/homebridge-pilight/node_modules/utf-8-validate
> node-gyp-build

+ homebridge-pilight@2.0.0
+ homebridge-info@1.2.0
added 97 packages from 87 contributors in 8.168s
[10/9/2020, 1:17:46 PM] Loaded config.json with 0 accessories and 4 platforms.
[10/9/2020, 1:17:46 PM] ---
[10/9/2020, 1:17:47 PM] Loaded plugin: homebridge-config-ui-x@4.19.0
[10/9/2020, 1:17:47 PM] Registering platform 'homebridge-config-ui-x.config'
[10/9/2020, 1:17:47 PM] ---
[10/9/2020, 1:17:47 PM] The plugin "homebridge-info" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!
[10/9/2020, 1:17:47 PM] Loaded plugin: homebridge-info@1.2.0
[10/9/2020, 1:17:47 PM] Registering platform 'homebridge-info.Info'
[10/9/2020, 1:17:47 PM] ---
[10/9/2020, 1:17:47 PM] Loaded plugin: homebridge-pilight@2.0.0
[10/9/2020, 1:17:47 PM] Registering accessory 'homebridge-pilight.pilight'
[10/9/2020, 1:17:47 PM] ---
[10/9/2020, 1:17:47 PM] Loading 4 platforms...
[10/9/2020, 1:17:47 PM] [Config] Initializing config platform...
[10/9/2020, 1:17:47 PM] [Config] Spawning homebridge-config-ui-x with PID 2009
[10/9/2020, 1:17:47 PM] Error loading platform requested in your config.json at position 2

[10/9/2020, 1:17:47 PM] Error: The requested platform 'FordPass' was not registered by any plugin.

at PluginManager.getPluginForPlatform (/usr/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
at /usr/lib/node_modules/homebridge/src/server.ts:387:37
at Array.forEach (<anonymous>)
at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:374:27)
at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:153:29)
at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
[10/9/2020, 1:17:47 PM] Got SIGTERM, shutting down Homebridge...
[0;37m[10/9/2020, 1:17:50 PM] [0m[0;36m[Config][0m [0;33mHomebridge Config UI X v4.19.0 is listening on 0.0.0.0 port 8124[0m
/usr/bin/homebridge -> /usr/lib/node_modules/homebridge/bin/homebridge
+ homebridge@1.1.6
updated 1 package in 4.381s
Hit:1 http://security.ubuntu.com/ubuntu eoan-security InRelease
Hit:2 https://deb.nodesource.com/node_12.x bionic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu eoan InRelease
Hit:4 http://archive.ubuntu.com/ubuntu eoan-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu eoan-backports InRelease
Reading package lists...
File '/root/.homebridge/config.json' already there; not retrieving.
Reading package lists...
Building dependency tree...
Reading state information...
ffmpeg is already the newest version (7:4.1.4-1build2).

0 upgraded, 0 newly installed, 0 to remove and 66 not upgraded.
+ homebridge-info@1.2.0
+ homebridge-pilight@2.0.0
updated 2 packages in 5.063s
[10/9/2020, 1:54:52 PM] Loaded config.json with 0 accessories and 4 platforms.
[10/9/2020, 1:54:52 PM] ---
[10/9/2020, 1:54:52 PM] Loaded plugin: homebridge-config-ui-x@4.19.0
[10/9/2020, 1:54:52 PM] Registering platform 'homebridge-config-ui-x.config'
[10/9/2020, 1:54:52 PM] ---
[10/9/2020, 1:54:52 PM] The plugin "homebridge-info" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!
[10/9/2020, 1:54:52 PM] Loaded plugin: homebridge-info@1.2.0
[10/9/2020, 1:54:52 PM] Registering platform 'homebridge-info.Info'
[10/9/2020, 1:54:52 PM] ---
[10/9/2020, 1:54:52 PM] Loaded plugin: homebridge-pilight@2.0.0
[10/9/2020, 1:54:52 PM] Registering accessory 'homebridge-pilight.pilight'
[10/9/2020, 1:54:52 PM] ---
[10/9/2020, 1:54:52 PM] Loading 4 platforms...
[10/9/2020, 1:54:52 PM] [Config] Initializing config platform...
[10/9/2020, 1:54:52 PM] [Config] Spawning homebridge-config-ui-x with PID 369
[10/9/2020, 1:54:52 PM] Error loading platform requested in your config.json at position 2

[10/9/2020, 1:54:52 PM] Error: The requested platform 'FordPass' was not registered by any plugin.

at PluginManager.getPluginForPlatform (/usr/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
at /usr/lib/node_modules/homebridge/src/server.ts:387:37
at Array.forEach (<anonymous>)
at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:374:27)
at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:153:29)
at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
[10/9/2020, 1:54:52 PM] Got SIGTERM, shutting down Homebridge...
[0;37m[10/9/2020, 1:54:54 PM] [0m[0;36m[Config][0m [0;33mHomebridge Config UI X v4.19.0 is listening on 0.0.0.0 port 8124[0m
/usr/bin/homebridge -> /usr/lib/node_modules/homebridge/bin/homebridge
+ homebridge@1.1.6
updated 1 package in 4.074s
Hit:1 http://security.ubuntu.com/ubuntu eoan-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu eoan InRelease
Hit:3 https://deb.nodesource.com/node_12.x bionic InRelease
Hit:4 http://archive.ubuntu.com/ubuntu eoan-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu eoan-backports InRelease
Reading package lists...
File '/root/.homebridge/config.json' already there; not retrieving.
Reading package lists...
Building dependency tree...
Reading state information...
ffmpeg is already the newest version (7:4.1.4-1build2).

0 upgraded, 0 newly installed, 0 to remove and 66 not upgraded.
+ homebridge-info@1.2.0
+ homebridge-pilight@2.0.0
updated 2 packages in 5.199s
[10/9/2020, 11:36:09 PM] Loaded config.json with 0 accessories and 4 platforms.
[10/9/2020, 11:36:09 PM] ---
[10/9/2020, 11:36:10 PM] Loaded plugin: homebridge-config-ui-x@4.19.0
[10/9/2020, 11:36:10 PM] Registering platform 'homebridge-config-ui-x.config'
[10/9/2020, 11:36:10 PM] ---
[10/9/2020, 11:36:10 PM] The plugin "homebridge-info" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!
[10/9/2020, 11:36:10 PM] Loaded plugin: homebridge-info@1.2.0
[10/9/2020, 11:36:10 PM] Registering platform 'homebridge-info.Info'
[10/9/2020, 11:36:10 PM] ---
[10/9/2020, 11:36:10 PM] Loaded plugin: homebridge-pilight@2.0.0
[10/9/2020, 11:36:10 PM] Registering accessory 'homebridge-pilight.pilight'
[10/9/2020, 11:36:10 PM] ---
[10/9/2020, 11:36:10 PM] Loading 4 platforms...
[10/9/2020, 11:36:10 PM] [Config] Initializing config platform...
[10/9/2020, 11:36:10 PM] [Config] Spawning homebridge-config-ui-x with PID 369
[10/9/2020, 11:36:10 PM] Error loading platform requested in your config.json at position 2

[10/9/2020, 11:36:10 PM] Error: The requested platform 'FordPass' was not registered by any plugin.

at PluginManager.getPluginForPlatform (/usr/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
at /usr/lib/node_modules/homebridge/src/server.ts:387:37
at Array.forEach (<anonymous>)
at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:374:27)
at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:153:29)
at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
[10/9/2020, 11:36:10 PM] Got SIGTERM, shutting down Homebridge...
[0;37m[10/9/2020, 11:36:11 PM] [0m[0;36m[Config][0m [0;33mHomebridge Config UI X v4.19.0 is listening on 0.0.0.0 port 8124[0m

**Comment by adriancable** [comment]
@joetlawson - in case you are interested, from your original log the FordPass plug-in was crashing Homebridge. That's why your other Homebridge devices (including homebridge-nest) were not showing up.
