### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by BREEZLET** [chrisjshull/homebridge-nest#319]
Hello, I got this message after I updated the Nest plugin and now my Homebridge won't start because of this issue. I am using the Nest account login (not Google login) for this plugin.

```
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: ada38093-df2f-4ced-80a9-b01f00529a6a
    at Bridge.Accessory._this.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:419:15)
    at cachedPlatformAccessories.cachedPlatformAccessories.filter.accessory (/usr/lib/node_modules/homebridge/src/server.ts:308:19)
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/lib/node_modules/homebridge/src/server.ts:268:69)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:156:10)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

**Comment by adriancable** [comment]
It could be the Homebridge accessory cache has got mangled somehow. Can you try deleting ~/.homebridge/accessories/cachedAccessories and run Homebridge again?

**Comment by BREEZLET** [comment]
I deleted the file and it works again. Even on a restart. Thank you! Much appreciated.
