### ISSUE TITLE
FetchError: request failed

### ISSUE THREAD

**Issue by Glitch482** [chrisjshull/homebridge-nest#339]
On homebridge-chamberlain v1.6.1 w/ RPI4/HomeBridge : Plugin works, but keep seeing the follow red errors in my logs (2 Garage Doors). Seems to happen about every couple of hours or so. Anyone know why this is happening? Getting strong Wifi signal in garage. 

`[24/11/2020, 17:48:13] [Garage Door 1] FetchError: request to https://api.myqdevice.com/api/v5.1/Accounts/fa611501-db28-4748-ba51-0d576f811040/devices/[DEVICE ID REMOVED] failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}`

`[24/11/2020, 20:47:12] [Garage Door 2] FetchError: request to https://api.myqdevice.com/api/v5.1/Accounts/fa611501-db28-4748-ba51-0d576f811040/devices/[DEVICE ID REMOVED] failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
`

Direct link in a browser gets the following message: 

`code | "401.102"
-- | --
message | "Unauthorized"
description | "The current call is Unauthorized."
`

Any help is appreciated.

**Comment by adriancable** [comment]
@Glitch482 - I have a hard enough time finding good answers to questions people have about my own plug-in, let alone finding good answers to questions you may have about a plug-in that I know nothing about! Better to try in the homebridge-chamberlain Github issues instead of here, maybe?
