### ISSUE TITLE
Error in loading Plugin 

### ISSUE THREAD

**Issue by markbajaj** [chrisjshull/homebridge-nest#34]
Today I randomly got an error when loading the plugin, that is naturally causing my whole homebridge instance to not start.

`Apr  8 09:32:10 HomeBridge2018 homebridge[18784]: [2018-4-8 09:32:10] ERROR LOADING PLUGIN homebridge-nest:
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]: [2018-4-8 09:32:10] /usr/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/map.js:130
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]: MappingPromiseArray.0rototypg.preservedValues = function (#011 {
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:                    ^^
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]: SyntaxError: Invalid or unexpected token
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:     at new Script (vm.js:51:7)
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:     at createScript (vm.js:136:10)
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:     at Object.runInThisContext (vm.js:197:10)
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:     at Module._compile (module.js:613:28)
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:     at Object.Module._extensions..js (module.js:660:10)
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:     at Module.load (module.js:561:32)
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:     at tryModuleLoad (module.js:501:12)
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:     at Function.Module._load (module.js:493:3)
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:     at Module.require (module.js:593:17)
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:     at require (internal/module.js:11:18)
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:     at module.exports (/usr/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:737:1)
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/bluebird.js:9:36)
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:     at Module._compile (module.js:649:30)
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:     at Object.Module._extensions..js (module.js:660:10)
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:     at Module.load (module.js:561:32)
Apr  8 09:32:10 HomeBridge2018 homebridge[18784]:     at tryModuleLoad (module.js:501:12)`

Later on in the log the following is displayed:

`Apr  8 09:32:12 HomeBridge2018 homebridge[18784]: /usr/lib/node_modules/homebridge/lib/api.js:122
Apr  8 09:32:12 HomeBridge2018 homebridge[18784]:       throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
Apr  8 09:32:12 HomeBridge2018 homebridge[18784]:       ^
Apr  8 09:32:12 HomeBridge2018 homebridge[18784]: Error: The requested platform 'Nest' was not registered by any plugin.
Apr  8 09:32:12 HomeBridge2018 homebridge[18784]:     at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
Apr  8 09:32:12 HomeBridge2018 homebridge[18784]:     at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:294:45)
Apr  8 09:32:12 HomeBridge2018 homebridge[18784]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
Apr  8 09:32:12 HomeBridge2018 homebridge[18784]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
Apr  8 09:32:12 HomeBridge2018 homebridge[18784]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr  8 09:32:12 HomeBridge2018 homebridge[18784]:     at Module._compile (module.js:649:30)
Apr  8 09:32:12 HomeBridge2018 homebridge[18784]:     at Object.Module._extensions..js (module.js:660:10)
Apr  8 09:32:12 HomeBridge2018 homebridge[18784]:     at Module.load (module.js:561:32)
Apr  8 09:32:12 HomeBridge2018 homebridge[18784]:     at tryModuleLoad (module.js:501:12)
Apr  8 09:32:12 HomeBridge2018 homebridge[18784]:     at Function.Module._load (module.js:493:3)
Apr  8 09:32:12 HomeBridge2018 homebridge[18784]:     at Function.Module.runMain (module.js:690:10)
Apr  8 09:32:12 HomeBridge2018 homebridge[18784]:     at startup (bootstrap_node.js:194:16)
Apr  8 09:32:12 HomeBridge2018 homebridge[18784]:     at bootstrap_node.js:666:3
Apr  8 09:32:12 HomeBridge2018 systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Apr  8 09:32:12 HomeBridge2018 systemd[1]: homebridge.service: Unit entered failed state.`

I have  the following versions:
`pi@HomeBridge2018:~ $ node -v
v9.10.1
pi@HomeBridge2018:~ $ npm -v
5.6.0
`

Raspberry Pi 3:
`pi@HomeBridge2018:~ $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"`

What I have tried:

- Restarting the HomeBridge Raspberry Pi

- Reinstalling homebridge-nest
- Removing homebridge-nest 
- Reinstalling homebridge-nest after reinstall

If I remove the Nest config from the config.json it works fine, so it does appear to be an issue with this particular plugin. I didn't update or do anything to the Pi, this just started happening.

Could you advise?

Thanks

**Comment by markbajaj** [comment]
I have just corrected what looked like a typo in the map.js (corruption maybe?) 

`Apr 8 09:32:10 HomeBridge2018 homebridge[18784]: [2018-4-8 09:32:10] ERROR LOADING PLUGIN homebridge-nest: Apr 8 09:32:10 HomeBridge2018 homebridge[18784]: [2018-4-8 09:32:10] /usr/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/map.js:130 Apr 8 09:32:10 HomeBridge2018 homebridge[18784]: **MappingPromiseArray.0rototypg.preservedValues** = function (#011 { Apr 8 09:32:10 HomeBridge2018 homebridge[18784]: ^^ `

I changed it to **MappingPromiseArray.prototype.preservedValues**
and now this error is thrown

`Apr  8 09:57:53 HomeBridge2018 homebridge[20335]: [2018-4-8 09:57:53] /usr/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/map.js:131
Apr  8 09:57:53 HomeBridge2018 homebridge[20335]:     return this._preservedValues;
Apr  8 09:57:53 HomeBridge2018 homebridge[20335]:            ^^^^
`

**Comment by markbajaj** [comment]
I have now fixed this. 

The plugin was installed in more than one place. Somehow after a log of messing around with npm switches I managed to remove it and stop it form loading. 

Once I did that I could install it again with no issues.

**Comment by markbajaj** [comment]
This can be closed
