### ISSUE TITLE
Apple Home Scenes using Nest Learning Thermostat Turning Off

### ISSUE THREAD

**Issue by JeffroDB** [chrisjshull/homebridge-nest#346]
I have a Nest Thermostat set to Fahrenheit and incorporate it into Apple Home via the Homebridge Nest plugin. It works perfectly but I've just encountered some strange behavior when incorporating it into some very basic Apple Home Scenes.

I've created three Apple Home scenes, all having the Nest Thermometer as the only accessory:

- "HVAC Off" : Sets thermostat's mode to "Off"
- "HVAC Heat" :  Sets thermostat's mode to "Heat" and sets target heating temp to 74F degrees
- "HVAC Cool"  : Sets thermostat's mode to "Cool" and sets target cooling temp to 78F degrees

I guess before I go on I need to explain how I expect an Apple Home "Scene" to behave visually when finger-tapped in the iOS Apple Home app. If the scene is "off" it's icon appears normally. If the scene is "on" it's icon is very much visually brightened. And most importantly for the purpose of this posting, the brightness (or lack thereof) that signifies the "on" or "off" state of the scene persists.

Here's the strange behavior I'm experiencing:
 
- My "HVAC Off" scene, when tapped, visually persists.
- My "HVAC Heat" and "HVAC Cool" scenes, when tapped, blink on, icons turning bright, but then, a few seconds later, revert to the visual "off" state. The underlying changes to the thermostat's "mode" and target temperatures are accomplished. 

Include with your bug report this version info:
Household iOS and ipadOS @ 14.3
Homepod Home Hub @ 14.3
macOS running Homebridge @ 11.1
Node .js @ 14.15.3
NPM @ 6.14.10
Homebridge Nest @ 4.5.1
Homebridge Nest using Google Account
Debug.Verbose is set
Nest Thermostat set to Fahrenheit

I truncated my log and restarted Homebridge and immediately tapped my "HVAC Heat" Apple Home scene described above. Here's the log, sorry about the other plug-in stuff:

12/26/2020, 7:53:30 AM] [Homebridge UI] Homebridge log truncated by admin.
[12/26/2020, 7:53:39 AM] [Homebridge UI] Homebridge restart request received
[12/26/2020, 7:53:39 AM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[12/26/2020, 7:53:39 AM] [HB Supervisor] Sending SIGTERM to Homebridge
[12/26/2020, 7:53:39 AM] Got SIGTERM, shutting down Homebridge...
[12/26/2020, 7:53:44 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[12/26/2020, 7:53:49 AM] [HB Supervisor] Restarting Homebridge...
[12/26/2020, 7:53:49 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[12/26/2020, 7:53:49 AM] [HB Supervisor] Started Homebridge v1.1.7 with PID: 2498
[12/26/2020, 7:53:49 AM] Loaded config.json with 22 accessories and 3 platforms.
[12/26/2020, 7:53:49 AM] ---
[12/26/2020, 7:53:49 AM] Loaded plugin: homebridge-config-ui-x@4.36.0
[12/26/2020, 7:53:49 AM] Registering platform 'homebridge-config-ui-x.config'
[12/26/2020, 7:53:49 AM] ---
[12/26/2020, 7:53:49 AM] Loaded plugin: homebridge-dummy@0.4.1
[12/26/2020, 7:53:49 AM] Registering accessory 'homebridge-dummy.DummySwitch'
[12/26/2020, 7:53:49 AM] ---
[12/26/2020, 7:53:49 AM] Loaded plugin: homebridge-messenger@0.0.6
[12/26/2020, 7:53:49 AM] Registering accessory 'homebridge-messenger.HomebridgeMessenger'
[12/26/2020, 7:53:49 AM] ---
[12/26/2020, 7:53:49 AM] Loaded plugin: homebridge-nest@4.5.1
[12/26/2020, 7:53:50 AM] Registering platform 'homebridge-nest.Nest'
[12/26/2020, 7:53:50 AM] ---
[12/26/2020, 7:53:50 AM] Loaded plugin: homebridge-plugin-eufy-security@0.1.6
[12/26/2020, 7:53:50 AM] Registering platform 'homebridge-plugin-eufy-security.EufySecurityHomebridgePlugin'
[12/26/2020, 7:53:50 AM] ---
[12/26/2020, 7:53:50 AM] Loading 3 platforms...
[12/26/2020, 7:53:50 AM] [Config] Initializing config platform...
[12/26/2020, 7:53:50 AM] [Config] Running in Service Mode
[12/26/2020, 7:53:50 AM] [Nest] Initializing Nest platform...
[12/26/2020, 7:53:50 AM] [EufySecurityHomebridgePlugin] Initializing EufySecurityHomebridgePlugin platform...
[12/26/2020, 7:53:50 AM] Loading 22 accessories...
[12/26/2020, 7:53:50 AM] [Messenger] Initializing HomebridgeMessenger accessory...
[12/26/2020, 7:53:50 AM] [Messenger] Added Main Switch : Messenger
[12/26/2020, 7:53:50 AM] [Messenger] Main Switch status : false
[12/26/2020, 7:53:50 AM] [Messenger] Added pushover : undefined
[12/26/2020, 7:53:50 AM] [EveningSwitch] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [EveningSwitch] Setting switch to false
[12/26/2020, 7:53:50 AM] [Front Guests] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Front Guests] Setting switch to false
[12/26/2020, 7:53:50 AM] [Smooth Jazz] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Smooth Jazz] Setting switch to false
[12/26/2020, 7:53:50 AM] [Resume] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Pause] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Piano Jazz] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Piano Jazz] Setting switch to false
[12/26/2020, 7:53:50 AM] [My Jazz Favs] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [My Jazz Favs] Setting switch to false
[12/26/2020, 7:53:50 AM] [Classical Baroque] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Classical Baroque] Setting switch to false
[12/26/2020, 7:53:50 AM] [Stacy Kent] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Stacy Kent] Setting switch to false
[12/26/2020, 7:53:50 AM] [John Pizzarelli] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [John Pizzarelli] Setting switch to false
[12/26/2020, 7:53:50 AM] [Country] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Country] Setting switch to false
[12/26/2020, 7:53:50 AM] [Jeff Golum] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Jeff Golum] Setting switch to false
[12/26/2020, 7:53:50 AM] [Guitar Jazz] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Guitar Jazz] Setting switch to false
[12/26/2020, 7:53:50 AM] [Matt Bianco] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Matt Bianco] Setting switch to false
[12/26/2020, 7:53:50 AM] [Pat Metheny] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Pat Metheny] Setting switch to true
[12/26/2020, 7:53:50 AM] [Gypsy Jazz] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Gypsy Jazz] Setting switch to false
[12/26/2020, 7:53:50 AM] [WSIE] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [WSIE] Setting switch to false
[12/26/2020, 7:53:50 AM] [Oldies] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Oldies] Setting switch to false
[12/26/2020, 7:53:50 AM] [Christmas] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Christmas] Setting switch to false
[12/26/2020, 7:53:50 AM] [Blue Guests] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Blue Guests] Setting switch to false
[12/26/2020, 7:53:50 AM] [Globe Shutoff] Initializing DummySwitch accessory...
[12/26/2020, 7:53:50 AM] [Nest] Fetching Nest devices.
[12/26/2020, 7:53:50 AM] [EufySecurityHomebridgePlugin] push client disabled
Setup Payload:
X-HM://0024JWWRBPCHK
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 654-74-775 │     
    └────────────┘     
                       
[12/26/2020, 7:53:50 AM] Homebridge is running on port 51302.
(node:2498) UnhandledPromiseRejectionWarning: Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 26052 - need validate code
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2498) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2498) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12/26/2020, 7:53:55 AM] [Nest] initing thermostat (P) "Hallway Thermostat": deviceId: 6416660000C31396 structureId: d8d47150-fe79-11e9-a94c-0a65a179e8d8
[12/26/2020, 7:53:55 AM] [Nest] initing temp_sensor (P) "Living Room": deviceId: 18B430C50A8970EE structureId: d8d47150-fe79-11e9-a94c-0a65a179e8d8
[12/26/2020, 7:57:56 AM] [Nest] Setting cooling threshold temperature to 23.3 °C / 73.94 °F
[12/26/2020, 7:57:56 AM] [Nest] Setting heating threshold temperature to 21.1 °C / 69.98 °F
[12/26/2020, 7:57:56 AM] [Nest] Setting temperature to 23.5 °C / 74.3 °F

**Comment by JeffroDB** [comment]
I'm going to close this and mark it down as an Apple Home deficiency in C <> F conversions. I was able to use the plugin and Home+ to create an Apple Home heating scene targeting Heat and 74.3F and it works as expected. Great plugin!
