### ISSUE TITLE
Max Temp In Auto Mode

### ISSUE THREAD

**Issue by sullimander** [chrisjshull/homebridge-nest#40]
**To Reproduce**

Using the latest version of homebridge-nest (2.1.3)

1. Set the Nest thermostat to auto mode in the Home app
2. Attempt to set the max (cool) temperature, the max is 77° F in the Home app, but 90° F in the Nest app.
3. Set the Nest thermostat to cool mode in the Home app
4. Attempt to set the max temperature, the max is 100° F in the Home app, but 90° F in the Nest app.

**Expected behavior**

The min and max temperatures in the Home app should match the min and max temperatures in the Nest app.

Include with your bug report this version info:
```sh
node --version
v8.11.2

homebridge --version
0.4.43
```

Screenshots:

![img_2735](https://user-images.githubusercontent.com/39138/41669197-1bc8e224-7466-11e8-8f24-bd0e2b4e1fd5.png)
![img_2737](https://user-images.githubusercontent.com/39138/41669199-1bfd3cfe-7466-11e8-9e30-0f1d0e50a1ac.png)
![img_2738](https://user-images.githubusercontent.com/39138/41669201-1c159b00-7466-11e8-891d-40002639976a.png)

```
[2018-6-20 08:42:02] [Nest] Temperature set to 37.8 { Error: TEMPERATURE F VALUE IS TOO HIGH: %S: {"error":"Temperature F value is too high: 100.0","type":"https://developer.nest.com/documenta
tion/cloud/error-messages#high-f-value","message":"Temperature F value is too high: 100.0","instance":"3920e78e-16a1-4899-8b7a-9d3a1880d96c","details":{"tempF":"100.0"}}                       
    at /homebridge/node_modules/firebase/lib/firebase-node.js:226:115                                                                                                                           
    at ec (/homebridge/node_modules/firebase/lib/firebase-node.js:52:165)                                                                                                                       
    at Pi (/homebridge/node_modules/firebase/lib/firebase-node.js:226:23)                                                                                                                       
    at /homebridge/node_modules/firebase/lib/firebase-node.js:221:404                                                                                                                           
    at /homebridge/node_modules/firebase/lib/firebase-node.js:184:355                                                                                                                           
    at Rh.h.Jd (/homebridge/node_modules/firebase/lib/firebase-node.js:186:104)                                                                                                                 
    at Fh.Jd (/homebridge/node_modules/firebase/lib/firebase-node.js:176:364)                                                                                                                   
    at wh.Jg (/homebridge/node_modules/firebase/lib/firebase-node.js:174:280)                                                                                                                   
    at zh (/homebridge/node_modules/firebase/lib/firebase-node.js:168:464)                                                                                                                      
    at Client.Ka.onmessage (/homebridge/node_modules/firebase/lib/firebase-node.js:167:321)                                                                                                     
    at Client.dispatchEvent (/homebridge/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)                                                        
    at Client._receiveMessage (/homebridge/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)                                                                  
    at Client.<anonymous> (/homebridge/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)                                                                       
    at emitOne (events.js:121:20)                                                                                                                                                               
    at Client.emit (events.js:211:7)                                                                                                                                                            
    at Client.<anonymous> (/homebridge/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)                                     
    at pipe (/homebridge/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)                         
    at Pipeline._loop (/homebridge/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)                
    at Pipeline.processIncomingMessage (/homebridge/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8
)                                                                                                                                                                                               
    at Extensions.processIncomingMessage (/homebridge/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions
.js:133:20)                                                                                                                                                                                     
    at Client._emitMessage (/homebridge/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)                                    
    at Client._emitFrame (/homebridge/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)                                      
  cause: { Error: TEMPERATURE F VALUE IS TOO HIGH: %S: {"error":"Temperature F value is too high: 100.0","type":"https://developer.nest.com/documentation/cloud/error-messages#high-f-value","me
ssage":"Temperature F value is too high: 100.0","instance":"3920e78e-16a1-4899-8b7a-9d3a1880d96c","details":{"tempF":"100.0"}}                                                                  
    at /homebridge/node_modules/firebase/lib/firebase-node.js:226:115                                                                                                                           
    at ec (/homebridge/node_modules/firebase/lib/firebase-node.js:52:165)                                                                                                                       
    at Pi (/homebridge/node_modules/firebase/lib/firebase-node.js:226:23)                                                                                                                       
    at /homebridge/node_modules/firebase/lib/firebase-node.js:221:404                                                                                                                           
    at /homebridge/node_modules/firebase/lib/firebase-node.js:184:355                                                                                                                           
    at Rh.h.Jd (/homebridge/node_modules/firebase/lib/firebase-node.js:186:104)                                                                                                                 
    at Fh.Jd (/homebridge/node_modules/firebase/lib/firebase-node.js:176:364)                                                                                                                   
    at wh.Jg (/homebridge/node_modules/firebase/lib/firebase-node.js:174:280)                                                                                                                   
    at zh (/homebridge/node_modules/firebase/lib/firebase-node.js:168:464)                                                                                                                      
    at Client.Ka.onmessage (/homebridge/node_modules/firebase/lib/firebase-node.js:167:321)                                                                                                     
    at Client.dispatchEvent (/homebridge/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)                                                        
    at Client._receiveMessage (/homebridge/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)                                                                  
    at Client.<anonymous> (/homebridge/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)                                                                       
    at emitOne (events.js:121:20)                                                                                                                                                               
    at Client.emit (events.js:211:7)                                                                                                                                                            
    at Client.<anonymous> (/homebridge/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)                                     
    at pipe (/homebridge/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)                         
    at Pipeline._loop (/homebridge/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)                
    at Pipeline.processIncomingMessage (/homebridge/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8
)                                                                                                                                                                                               
    at Extensions.processIncomingMessage (/homebridge/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions
.js:133:20)                                                                                                                                                                                     
    at Client._emitMessage (/homebridge/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)                                    
    at Client._emitFrame (/homebridge/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19) code: 'TEMPERATURE F VALUE IS TOO HIG
H: %S' },                                                                                                                                                                                       
  isOperational: true,                                                                                                                                                                          
  code: 'TEMPERATURE F VALUE IS TOO HIGH: %S' }  
```

**Comment by chrisjshull** [comment]
Please fill out the bug report template. You can find a copy of the template here: https://github.com/chrisjshull/homebridge-nest/issues/new?template=Bug_report.md
(copy and paste to this bug)

**Comment by sullimander** [comment]
@chrisjshull updated with more info. Let me know if you need more details.

**Comment by adriancable** [comment]
Fixed in the latest commit on github. (not yet on npmjs)

**Comment by adriancable** [comment]
Closing for now as believe resolved.
