### ISSUE TITLE
Cannot read property 'addService' of undefined

### ISSUE THREAD

**Issue by jasehigh** [chrisjshull/homebridge-nest#401]
I've just set up my first Nest products (2 x Nest Protects) but I'm struggling to set-up homebridge-nest.

When I start the homebridge service, all seems well but then I get the following errors:

```
[Nest] TypeError: Cannot read property 'addService' of undefined
    at new NestDeviceAccessory (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:52:62)
    at new NestProtectAccessory (/usr/local/lib/node_modules/homebridge-nest/lib/nest-protect-accessory.js:23:9)
    at NestPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/index.js:60:47)
    at NestPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/index.js:70:17)
    at API.NestPlatform.api.on (/usr/local/lib/node_modules/homebridge-nest/index.js:99:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)

[Nest] NOTE: Because we couldn't connect to the Nest service, your Nest devices in HomeKit will not be responsive.
```

My config.json looks correct, and I'm confident I've got the right values for issueToken and cookies:

```
{
	"bridge": {
		"name": "Nest",
		"username": "xxx",
		"port": xxx,
		"pin": "xxx"
	},
	"platforms": [{
		"platform": "Nest",
		"options": [ "HomeAway.Disable" ],
		"googleAuth": {
			"issueToken": "xxx",
			"cookies": "xxx"
		}
	}]
}
```

My versions are:
homebridge 0.4.50
homebridge-nest 4.5.3
node 10.15.3
npm 6.13.7

I'm running home bridge on a macMini (v10.10.5).

Any assistance is greatly appreciated.

Jase.

**Comment by jasehigh** [comment]
Updated homebridge to 0.4.53, still no joy...

**Comment by jasehigh** [comment]
Downgrading to homebridge-nest 4.4.6 removes this error, but its replaced with:

`[Nest] When using googleAuth, you must provide issueToken, cookies and apiKey in config.json. Please see README.md for instructions`

I can see the "Remove need for apiKey in configuration" in the change log.

**Comment by jasehigh** [comment]
Downgrading to home bridge 4.4.6 and following the additional instructions to get the apiKey has solved the issue:

```
11. In the 'Filter' box, enter `issue_jwt`
12. Click on the last `issue_jwt` call.
13. In the Headers tab, under Request Headers, copy the entire `x-goog-api-key` (do not include the `x-goog-api-key:` name). This is your `"apiKey"` in `config.json`.
```
