### ISSUE TITLE
"The requested platform 'Nest' was not registered by any plugin."

### ISSUE THREAD

**Issue by brentleeper** [chrisjshull/homebridge-nest#41]
Homebridge does not recognize the nest plug in after upgrading nodejs. 

Error: The requested platform 'Nest' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server.str.replace.Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:45)
    at Server.str.replace.Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by chrisjshull** [comment]
Hi, please include node version, and full homebridge logs.

**Comment by brentleeper** [comment]
4.5.0 and where are the logs located?

**Comment by chrisjshull** [comment]
Try using node version 8.

**Comment by brentleeper** [comment]
Out of time today, will do soon.

**Comment by brentleeper** [comment]
I upgraded to node 8.0.0 and the issue persists. Homebridge fails before any log is generated.

**Comment by brentleeper** [comment]
You can close this issue, it was due to my SSD being corrupted.
