### ISSUE TITLE
Home+ Automation Crashing Plugin because "Temperature Display Units" is enabled

### ISSUE THREAD

**Issue by mrjackyliang** [chrisjshull/homebridge-nest#415]
**Describe the bug**

**To Reproduce**
1. Set temperature to 85F

**Expected behavior**
To change to 85F

Include with your bug report this version info:
```sh
node v14.16.0
homebridge v1.3.4
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
```
[7/7/2021, 5:55:14 PM] [Nest] Setting cooling threshold temperature to 29.5 °C / 85.10000000000001 °F
[7/7/2021, 5:55:16 PM] TypeError: Cannot set property 'enabled' of undefined
    at Connection.addToOutput (/homebridge/node_modules/homebridge-nest/lib/nest-connection.js:1657:46)
    at /homebridge/node_modules/homebridge-nest/lib/nest-connection.js:1701:33
    at Array.forEach (<anonymous>)
    at Connection.legacyToProtobufUpdate (/homebridge/node_modules/homebridge-nest/lib/nest-connection.js:1675:14)
    at Connection.pushUpdates (/homebridge/node_modules/homebridge-nest/lib/nest-connection.js:1461:36)
    at Connection.pushUpdatesDebounced.debounce.maxWait (/homebridge/node_modules/homebridge-nest/lib/nest-connection.js:123:18)
    at invokeFunc (/homebridge/node_modules/homebridge-nest/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (/homebridge/node_modules/homebridge-nest/node_modules/lodash.debounce/index.js:207:14)
    at Timeout.timerExpired [as _onTimeout] (/homebridge/node_modules/homebridge-nest/node_modules/lodash.debounce/index.js:195:14)
    at listOnTimeout (internal/timers.js:554:17)
[7/7/2021, 5:55:16 PM] Got SIGTERM, shutting down Homebridge...
[7/7/2021, 5:55:21 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
```

**Comment by adriancable** [comment]
@mrjackyliang - what an odd one! Please tell me what model thermostat you're using, and what mode that thermostat is in. Does the problem only happen with 85 degrees (and not 84 degrees) or was that just an example?

**Comment by mrjackyliang** [comment]
Yeah, it used to just work. This is set with Home+. Let me try to adjust the temperature and I'll report back

**Comment by mrjackyliang** [comment]
<img width="1204" alt="Screen Shot 2021-07-07 at 7 42 56 PM" src="https://user-images.githubusercontent.com/9779803/124841570-8c12ea80-df5b-11eb-8e5d-847d7d50a4b1.png">

hmm adjusted it to something else, still crashed

**Comment by adriancable** [comment]
@mrjackyliang - can you kindly answer the other questions I asked about your config? (And also a new question - whether the same thing happens with Apple's Home app.) Because it doesn't happen to me, it's most likely due to something specific to your config. So, to go further you'll need to answer the questions I wrote about what the thermostat you have and what mode it's in. Without that information, I don't know where to go next. Thank you!

**Comment by mrjackyliang** [comment]
Woopsie! I totally forgot. I am using the Nest Thermostat E, 1st generation. I am using custom automation from Home+ that sets the cooling/heating and target temperature all at once.

Surprisingly when I turned off the "Temperature Display Units", the plugin doesn't crash anymore.

**Comment by adriancable** [comment]
@mrjackyliang - that's the missing piece of the puzzle! Changing the temperature display units on a protobuf API thermostat causes the crash.

I'm preparing a bunch of updates right now (including @Brandawg93's PR) and will fix this in the next update that I hope to get out in the next few days. Thanks for reporting this!

**Comment by mrjackyliang** [comment]
Ahh, cool! Thanks for the update 😀
