### ISSUE TITLE
login.js not working

### ISSUE THREAD

**Issue by cmb991** [chrisjshull/homebridge-nest#440]
Tried using login.js to get oauth but the module is not found

`pi@homebridge:/var/lib/homebridge $ node login.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/var/lib/homebridge/login.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}`

**Comment by adriancable** [comment]
Per the instructions you need to run 'node login.js' **where the homebridge-nest plug-in is installed**. Not where homebridge is installed.
