### ISSUE TITLE
Error: Cannot find module '/Users/jeffreybowman/login.js'

### ISSUE THREAD

**Issue by JeffroDB** [chrisjshull/homebridge-nest#443]
**Describe the bug**

I've been running the plugin for ages on my Mac using the "Google Account Cookies" method and overnight I apparently lost my cookies. I decided to uninstall/reinstall and this time use the "Google Account Refresh Token" method. When attempting to run "node login.js" I receive the error:  Cannot find module '/Users/jeffreybowman/login.js'

My node version is:  14.18.0

My Homebridge version is:  1.3.4

My Homebridge-nest version is: 4.6.2

This is pasted from Terminal:

% node login.js                 
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/Users/jeffreybowman/login.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by chaz-clark** [comment]
Here is how I got it to work:
1. clone the repo
2. in CMD or Terminal cd <path of login.js>
3. run node login.js

Note: I was missing the 'axios' package so I had to run `npm install axios`

**Comment by adriancable** [comment]
@chaz-clark - you don't need to jump through all those hoops. Just go to where the plug-in is already installed (by npm), and run `node login.js`. All the dependencies are already there and you don't need to do `npm install axios` or anything else.

**Comment by JeffroDB** [comment]
Adriancable, I learned that the hard way. :-)

The developer’s instructions need to make that clearer for noobs like myself. That said, it made me learn some things I hadn’t known.

**Comment by adriancable** [comment]
@JeffroDB - gotcha, I'll tweak the README and push an update in the next few minutes. Let me know if you think this makes more sense!

**Comment by JeffroDB** [comment]
Adriancable,

Very good! Thank you for working on a Sunday.

I’m so noobish I knew nothing of npm or node so my Sunday’s journey took me down some Google search rabbit holes that, like all rabbit holes, I had no idea existed yesterday. Live and learn!
