### ISSUE TITLE
Warning: unable to use REST API 

### ISSUE THREAD

**Issue by Beezwaad** [chrisjshull/homebridge-nest#484]
**Describe the bug**
For each Nest Protect device I get the error “Warning: unable to use REST API device XXXXXXX (topaz) due to missing required properties. 

Devices still show up in HomeKit. 

**To Reproduce**
1. Plugin version 4.6.3
2. Using Google Auth
3. Six Nest Protects

**Expected behavior**
No warnings

Include with your bug report this version info:
```sh
node --version 14.15.4
homebridge --version 1.3.8
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
@Beezwaad - this is very strange. What model of Nest Protects do you have? Feel free to reach out to me by email at adrian.cable@gmail.com, and we can debug via email.

**Comment by Beezwaad** [comment]
I have the latest battery-powered Nest protects.  When Hoimebridge restart did not work, I tried uninstalling/reinstalling the plugin (but using existing settings) and am not seeing that error after three days.  I still do see occasional API errors but they stop after retry:

[Nest] API observe: error Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
[25/12/2021, 20:39:36] [Nest] Retrying in 10 seconds.

**Comment by Beezwaad** [comment]
More examples:

——————————————
SUCCESSFUL LAUNCH
——————————————
[22/12/2021, 17:57:07] [Nest] Launched child bridge with PID 26908
[22/12/2021, 17:57:08] Registering platform 'homebridge-nest.Nest'
[22/12/2021, 17:57:08] [Nest] Loaded homebridge-nest v4.6.3 child bridge successfully
[22/12/2021, 17:57:08] Loaded 7 cached accessories from cachedAccessories.0ECCDA107824.
[22/12/2021, 17:57:08] [Nest] Fetching Nest devices.
[22/12/2021, 17:57:08] Homebridge v1.3.8 (HAP v0.9.7) (Nest) is running on port 39593.
[22/12/2021, 17:57:14] [Nest] initing home_away_sensor "Home Occupied": deviceId: b4a543a0-a1cf-11e5-8171-22000b06092b structureId: b4a543a0-a1cf-11e5-8171-22000b06092b
[22/12/2021, 17:57:14] [Nest] initing protect "Basement": deviceId: 18B4300041858F4C structureId: b4a543a0-a1cf-11e5-8171-22000b06092b
[22/12/2021, 17:57:14] [Nest] initing protect "Upstairs": deviceId: 18B43000418D121C structureId: b4a543a0-a1cf-11e5-8171-22000b06092b
[22/12/2021, 17:57:14] [Nest] initing protect "Office": deviceId: 18B43000418857AF structureId: b4a543a0-a1cf-11e5-8171-22000b06092b
[22/12/2021, 17:57:14] [Nest] initing protect "Guest Room": deviceId: 18B43000418AF839 structureId: b4a543a0-a1cf-11e5-8171-22000b06092b
[22/12/2021, 17:57:14] [Nest] initing protect "Upstairs": deviceId: 18B43000418872E8 structureId: b4a543a0-a1cf-11e5-8171-22000b06092b
[22/12/2021, 17:57:14] [Nest] initing protect "Downstairs": deviceId: 18B430004188780F structureId: b4a543a0-a1cf-11e5-8171-22000b06092b


——————————————
LATER ERRORS
——————————————
[25/12/2021, 20:39:36] [Nest] API observe: error Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
[25/12/2021, 20:39:36] [Nest] Retrying in 10 seconds.
[26/12/2021, 11:08:11] [Nest] API observe: error Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR
    at ClientHttp2Stream._destroy (internal/http2/core.js:2193:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:39:8)
    at Http2Stream.onStreamClose (internal/http2/core.js:512:12) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}
[26/12/2021, 11:08:11] [Nest] Retrying in 10 seconds.

**Comment by adriancable** [comment]
@Beezwaad ... what do your 'More examples' relate to? The log lines you posted (including the 'errors') are completely normal. The Internet is not 100% reliable and nothing you posted should result in any problem.

**Comment by Beezwaad** [comment]
Just wanted to show what errors I was seeing after successful authentication.   If this are normal, I am fine. 

Thank you for providing this plugin. 

Dave

**Comment by adriancable** [comment]
@Beezwaad - got it - thanks for the clarification! Those 'errors' are normal.

What isn't normal is your original issue about your Nest Protects missing required properties, so if you can still reproduce that and you'd like to debug, please shoot me an email - adrian.cable@gmail.com. Thanks!

**Comment by martijndierckx** [comment]
I've got the same issue after replacing my old protects with new ones:
`[Nest] Warning: unable to use REST API device ABCD....XYZ (topaz) due to missing required properties.`

I'll send you an email as well

**Comment by bradcerasani** [comment]
I'm experiencing this as well, but only after adding an older (2nd gen.) learning thermostat.

> Warning: unable to use REST API device [ID] (device) due to missing required properties.

Intervals:

<img width="1189" alt="Screen Shot 2022-01-17 at 19 16 48 copy" src="https://user-images.githubusercontent.com/468093/149857402-4b07cf48-e4c5-4b28-856c-9a50aeaf4f0d.png">

Thermostat model: Display-2.12
Software version: 5.9.4-5

No software update available.

4 newer thermostats and 7 protects are working fine.

**Comment by adriancable** [comment]
@bradcerasani - can you send me an email at adrian.cable@gmail.com so we can debug? Thanks!

**Comment by adriancable** [comment]
No response from OP by GitHub or email, so closing.
