### ISSUE TITLE
Cant Authorize Nest Account

### ISSUE THREAD

**Issue by slvrscoobie** [chrisjshull/homebridge-nest#523]
nest was authorized 
noticed today it wasn't working. 
I re-did the steps to get the cookie and urls. 
says its     
data: {
      error: 'invalid_request',
      error_description: 'Missing required parameter: scope'
    }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON],
  status: 400
}
[3/7/2022, 10:40:58 PM] [Nest] Access token acquisition via googleAuth failed (code 400).
[3/7/2022, 10:40:58 PM] [Nest] Unable to authenticate with Google/Nest.
**To Reproduce**
use nest cookie method - fails to authenticate

**Expected behavior**

Include with your bug report this version info:
```sh
node --version - v16.14.0
homebridge --version - 

Node.js Version | v16.13.1
-- | --
v6.14.15


```
Error: Request failed with status code 400
    at createError (/volume1/@appdata/homebridge/lib/node_modules/homebridge-nest/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/volume1/@appdata/homebridge/lib/node_modules/homebridge-nest/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/volume1/@appdata/homebridge/lib/node_modules/homebridge-nest/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  config: {

I also see this same Axios error when trying to google Login.JS method as well. 
nest-master-2/login.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'axios'
Require stack:
- /Users/Downloads/homebridge-nest-master-2/login.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/homebridge-nest-master-2/login.js:5:15)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/homebridge-nest-master-2/login.js' ]
}

**Comment by adriancable** [comment]
1. If you get an error with the cookies method it means you've not pasted the issueToken or cookies correctly. Without you sharing those, I have no way of telling you what you did wrong.

2. For the refresh token method, why are you running `node login.js` from the `/Users/brucebutkus/Downloads/homebridge-nest-master-2` folder? The instructions tell you to run `node login.js` from the folder where you have installed the plug-in, which from your cut-and paste is: `/volume1/@appdata/homebridge/lib/node_modules/homebridge-nest`

**Comment by slvrscoobie** [comment]
My cookie is the same method /‘copy paste from the last like 4 times I’ve done this. Not sure how I’m supposed to paste my cookie here as I don’t want to share it. 
it’s the same cookie:5 lines of text )without cookie included. And the url. It’s worked before. 

I’m not running home bridge on my Mac. It’s in a docket container on my synology. Not sure how I’d run your js from there. 
if you could remove my folder name it would be appreciated.

**Comment by adriancable** [comment]
@slvrscoobie - the issueToken URL in the above is incomplete. It stops at `home.nest.com` in your cut-and-paste but in the actual URL, there is other stuff after that. When I tried it just now after `home.nest.com` there was `&scope=openid%20profile%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fnest-account&ss_domain=https%3A%2F%2Fhome.nest.com&include_granted_scopes=true` which you've missed out.

Regarding running login.js on your Docker container, you'll need to SSH into the container and run it from there. If you want to run it from your Mac, you'll need to do `npm i` from the directory you downloaded the plug-in to first to install the dependencies, but there isn't really a reason to do it that way. Just run it in the container.

**Comment by slvrscoobie** [comment]
Ok. So Don’t stop at nest.com per instruction item 7 for cookie method?

**Comment by adriancable** [comment]
The instructions do say 'copy the entire `Request URL`' but since the query parameters can move around, I'll edit the README to make that clearer.

**Comment by slvrscoobie** [comment]
Roger. I’ll copy the whole thing and test. Thanks for the quick reply.

**Comment by adriancable** [comment]
Sure thing! Good luck.

**Comment by slvrscoobie** [comment]
Up and running, thanks for the assistance!
