### ISSUE TITLE
Support for Nest Protect smoke and CO alarm

### ISSUE THREAD

**Issue by ericxliu1990** [chrisjshull/homebridge-nest#529]
**Describe the bug**
Does this plugin has support for the Nest Protect smoke and CO alarm? I am getting error messages with the Nest Protect smoke and CO alarm. 

**To Reproduce**
1.  Pair a Nest Protect smoke and CO alarm device2. 
**Expected behavior**
Report the device as sensors or have proper error messages for not supporting.
Include with your bug report this version info:
```sh
node --version
homebridge --version
```
/homebridge # node --version
v16.14.0
/homebridge # homebridge --version
1.4.0
Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

[4/2/2022, 1:42:55 AM] [Nest] Warning: unable to use REST API device 18B4300000AABA44 (topaz) due to missing required properties.
[4/2/2022, 1:42:55 AM] [Nest] TypeError: Cannot set properties of undefined (setting 'device_id')
    at /homebridge/node_modules/homebridge-nest/lib/nest-connection.js:1223:46
    at Array.forEach (<anonymous>)
    at Connection.apiResponseToObjectTree (/homebridge/node_modules/homebridge-nest/lib/nest-connection.js:1154:48)
    at ClientHttp2Stream.<anonymous> (/homebridge/node_modules/homebridge-nest/lib/nest-connection.js:705:49)
    at ClientHttp2Stream.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at ClientHttp2Stream.Readable.push (node:internal/streams/readable:228:10)
    at Http2Stream.onStreamRead (node:internal/stream_base_commons:190:23)
[4/2/2022, 1:42:57 AM] [Nest] Warning: unable to use REST API device 18B4300000AABA44 (topaz) due to missing required properties.
[4/2/2022, 1:42:57 AM] [Nest] TypeError: Cannot set properties of undefined (setting 'device_id')
    at /homebridge/node_modules/homebridge-nest/lib/nest-connection.js:1223:46
    at Array.forEach (<anonymous>)
    at Connection.apiResponseToObjectTree (/homebridge/node_modules/homebridge-nest/lib/nest-connection.js:1154:48)
    at ClientHttp2Stream.<anonymous> (/homebridge/node_modules/homebridge-nest/lib/nest-connection.js:705:49)
    at ClientHttp2Stream.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at ClientHttp2Stream.Readable.push (node:internal/streams/readable:228:10)
    at Http2Stream.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by adriancable** [comment]
@ericxliu1990 - if you just ignore these warnings, do you see your Nest Protect devices in HomeKit? This looks to me like the plug-in picking up 'partially installed' devices, i.e. something that you scanned the QR code for then aborted before completing set-up.

If this is not the case and your Nest Protect devices don't appear in HomeKit, please send me an email at adrian.cable@gmail.com and I will help you get up and running. If I don't hear from you I will assume this is resolved.

**Comment by ericxliu1990** [comment]
Thanks for the response. I don't see any new devices added to Homebridge but I can see the device from the Nest app. 

Just to make sure to the device was not installed improperly. I factory reseted the device and install again. The issue persistent. 

Is there any logs I can provide to facilitate this debug?

**Comment by adriancable** [comment]
@ericxliu1990 - yes, but as per my previous request please email me at adrian.cable@gmail.com and I will tell you what I need you to get, and how. Github is not the right medium for this (can't exchange files etc.) and our debugging effort is not interesting to anyone else, only the end result which I will post here when we have made progress.

**Comment by adriancable** [comment]
Closing since unfortunately no contact from @ericxliu1990. Presumably the original issue has been fixed by the OP.
