### ISSUE TITLE
Temp Set Error When "Hey Siri set Nest to x"

### ISSUE THREAD

**Issue by brentleeper** [chrisjshull/homebridge-nest#67]
When telling Siri to set the nest temp to x, it instead sets a range of a seemingly random size with the x temp in the middle. There is also the following error in the console. 

[2018-10-11 21:59:32] [Nest] Queuing to set heating threshold temperature 23.3
[2018-10-11 21:59:32] [Nest] Queuing to set cooling threshold temperature 26.1
[2018-10-11 21:59:32] [Nest] Queuing to set temperature 23.3
FIREBASE WARNING: set at /devices/thermostats/blbAL4PNzZlzts-pr1KsvVRL8luSp1L2/target_temperature_low_f failed: Cannot set target low temperature '%s' higher than target high temperature '%s' 
[2018-10-11 21:59:37] [Nest] Heating threshold temperature set to 23.3 { Error: CANNOT SET TARGET LOW TEMPERATURE '%S' HIGHER THAN TARGET HIGH TEMPERATURE '%S': {"error":"Cannot set target low temperature '74.0' higher than target high temperature '72.0'","type":"https://developer.nest.com/documentation/cloud/error-messages#low-high-error","message":"Cannot set target low temperature '74.0' higher than target high temperature '72.0'","instance":"dfdafd78-b922-4321-b1e8-45d287690dbd","details":{"lowTemp":"74.0","highTemp":"72.0"}}
    at /node_modules/firebase/lib/firebase-node.js:226:115
    at ec (/node_modules/firebase/lib/firebase-node.js:52:165)
    at Pi (/node_modules/firebase/lib/firebase-node.js:226:23)
    at /node_modules/firebase/lib/firebase-node.js:221:404
    at /node_modules/firebase/lib/firebase-node.js:184:355
    at Rh.h.Jd (/node_modules/firebase/lib/firebase-node.js:186:104)
    at Fh.Jd (/node_modules/firebase/lib/firebase-node.js:176:364)
    at wh.Jg (/node_modules/firebase/lib/firebase-node.js:174:280)
    at zh (/node_modules/firebase/lib/firebase-node.js:168:464)
    at Client.Ka.onmessage (/node_modules/firebase/lib/firebase-node.js:167:321)
    at Client.dispatchEvent (/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
    at Client._receiveMessage (/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
    at Client.<anonymous> (/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
    at emitOne (events.js:121:20)
    at Client.emit (events.js:211:7)
    at Client.<anonymous> (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
    at pipe (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
    at Pipeline._loop (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)
    at Pipeline.processIncomingMessage (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)
    at Extensions.processIncomingMessage (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
    at Client._emitMessage (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
    at Client._emitFrame (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
    at Client.parse (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)
    at Client.parse (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/client.js:56:58)
    at IO.write (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/streams.js:80:16)
    at TLSSocket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
  cause: 
   { Error: CANNOT SET TARGET LOW TEMPERATURE '%S' HIGHER THAN TARGET HIGH TEMPERATURE '%S': {"error":"Cannot set target low temperature '74.0' higher than target high temperature '72.0'","type":"https://developer.nest.com/documentation/cloud/error-messages#low-high-error","message":"Cannot set target low temperature '74.0' higher than target high temperature '72.0'","instance":"dfdafd78-b922-4321-b1e8-45d287690dbd","details":{"lowTemp":"74.0","highTemp":"72.0"}}
    at /node_modules/firebase/lib/firebase-node.js:226:115
    at ec (/node_modules/firebase/lib/firebase-node.js:52:165)
    at Pi (/node_modules/firebase/lib/firebase-node.js:226:23)
    at /node_modules/firebase/lib/firebase-node.js:221:404
    at /node_modules/firebase/lib/firebase-node.js:184:355
    at Rh.h.Jd (/node_modules/firebase/lib/firebase-node.js:186:104)
    at Fh.Jd (/node_modules/firebase/lib/firebase-node.js:176:364)
    at wh.Jg (/node_modules/firebase/lib/firebase-node.js:174:280)
    at zh (/node_modules/firebase/lib/firebase-node.js:168:464)
    at Client.Ka.onmessage (/node_modules/firebase/lib/firebase-node.js:167:321)
    at Client.dispatchEvent (/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
    at Client._receiveMessage (/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
    at Client.<anonymous> (/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
    at emitOne (events.js:121:20)
    at Client.emit (events.js:211:7)
    at Client.<anonymous> (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
    at pipe (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
    at Pipeline._loop (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)
    at Pipeline.processIncomingMessage (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)
    at Extensions.processIncomingMessage (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
    at Client._emitMessage (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
    at Client._emitFrame (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
    at Client.parse (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)
    at Client.parse (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/client.js:56:58)
    at IO.write (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/streams.js:80:16)
    at TLSSocket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
     code: 'CANNOT SET TARGET LOW TEMPERATURE \'%S\' HIGHER THAN TARGET HIGH TEMPERATURE \'%S\'' },
  isOperational: true,
  code: 'CANNOT SET TARGET LOW TEMPERATURE \'%S\' HIGHER THAN TARGET HIGH TEMPERATURE \'%S\'' }
FIREBASE WARNING: set at /devices/thermostats/blbAL4PNzZlzts-pr1KsvVRL8luSp1L2/target_temperature_low_f failed: Cannot set target low temperature '%s' higher than target high temperature '%s' 
[2018-10-11 21:59:38] [Nest] Temperature set to 23.3 { Error: CANNOT SET TARGET LOW TEMPERATURE '%S' HIGHER THAN TARGET HIGH TEMPERATURE '%S': {"error":"Cannot set target low temperature '74.0' higher than target high temperature '72.0'","type":"https://developer.nest.com/documentation/cloud/error-messages#low-high-error","message":"Cannot set target low temperature '74.0' higher than target high temperature '72.0'","instance":"088d51c7-7cf4-4fbe-b6e5-ace8b658ffba","details":{"lowTemp":"74.0","highTemp":"72.0"}}
    at /node_modules/firebase/lib/firebase-node.js:226:115
    at ec (/node_modules/firebase/lib/firebase-node.js:52:165)
    at Pi (/node_modules/firebase/lib/firebase-node.js:226:23)
    at /node_modules/firebase/lib/firebase-node.js:221:404
    at /node_modules/firebase/lib/firebase-node.js:184:355
    at Rh.h.Jd (/node_modules/firebase/lib/firebase-node.js:186:104)
    at Fh.Jd (/node_modules/firebase/lib/firebase-node.js:176:364)
    at wh.Jg (/node_modules/firebase/lib/firebase-node.js:174:280)
    at zh (/node_modules/firebase/lib/firebase-node.js:168:464)
    at Client.Ka.onmessage (/node_modules/firebase/lib/firebase-node.js:167:321)
    at Client.dispatchEvent (/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
    at Client._receiveMessage (/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
    at Client.<anonymous> (/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
    at emitOne (events.js:121:20)
    at Client.emit (events.js:211:7)
    at Client.<anonymous> (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
    at pipe (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
    at Pipeline._loop (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)
    at Pipeline.processIncomingMessage (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)
    at Extensions.processIncomingMessage (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
    at Client._emitMessage (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
    at Client._emitFrame (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
    at Client.parse (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)
    at Client.parse (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/client.js:56:58)
    at IO.write (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/streams.js:80:16)
    at TLSSocket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
  cause: 
   { Error: CANNOT SET TARGET LOW TEMPERATURE '%S' HIGHER THAN TARGET HIGH TEMPERATURE '%S': {"error":"Cannot set target low temperature '74.0' higher than target high temperature '72.0'","type":"https://developer.nest.com/documentation/cloud/error-messages#low-high-error","message":"Cannot set target low temperature '74.0' higher than target high temperature '72.0'","instance":"088d51c7-7cf4-4fbe-b6e5-ace8b658ffba","details":{"lowTemp":"74.0","highTemp":"72.0"}}
    at /node_modules/firebase/lib/firebase-node.js:226:115
    at ec (/node_modules/firebase/lib/firebase-node.js:52:165)
    at Pi (/node_modules/firebase/lib/firebase-node.js:226:23)
    at /node_modules/firebase/lib/firebase-node.js:221:404
    at /node_modules/firebase/lib/firebase-node.js:184:355
    at Rh.h.Jd (/node_modules/firebase/lib/firebase-node.js:186:104)
    at Fh.Jd (/node_modules/firebase/lib/firebase-node.js:176:364)
    at wh.Jg (/node_modules/firebase/lib/firebase-node.js:174:280)
    at zh (/node_modules/firebase/lib/firebase-node.js:168:464)
    at Client.Ka.onmessage (/node_modules/firebase/lib/firebase-node.js:167:321)
    at Client.dispatchEvent (/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
    at Client._receiveMessage (/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
    at Client.<anonymous> (/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
    at emitOne (events.js:121:20)
    at Client.emit (events.js:211:7)
    at Client.<anonymous> (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
    at pipe (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
    at Pipeline._loop (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)
    at Pipeline.processIncomingMessage (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)
    at Extensions.processIncomingMessage (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
    at Client._emitMessage (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
    at Client._emitFrame (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
    at Client.parse (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)
    at Client.parse (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/client.js:56:58)
    at IO.write (/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/streams.js:80:16)
    at TLSSocket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
     code: 'CANNOT SET TARGET LOW TEMPERATURE \'%S\' HIGHER THAN TARGET HIGH TEMPERATURE \'%S\'' },
  isOperational: true,
  code: 'CANNOT SET TARGET LOW TEMPERATURE \'%S\' HIGHER THAN TARGET HIGH TEMPERATURE \'%S\'' }
[2018-10-11 21:59:38] [Nest] Cooling threshold temperature set to 26.1 null

**Comment by vasuvasu** [comment]
Re-install homebridge-nest to make sure you're on version 2.1.4. This was fixed back in late June, but I was on a previous version still.

**Comment by adriancable** [comment]
homebridge-nest 3.0.0 no longer uses Firebase so all should be OK.
