### ISSUE TITLE
Crashes caused by RangeError: Could not decode varint

### ISSUE THREAD

**Issue by vectronic** [chrisjshull/homebridge-nest#677]
**Describe the bug**

I am getting regular (roughly 1-2 occurrences per day) errors in the plugin causing Homebridge to exit and be restarted.

I have not changed anything with Nest or the plugin (except upgrades) for a long time and this has started occurring about 3 weeks ago...

**To Reproduce**
1.  Run homebridge with homebridge-nest plugin with the following config and then wait...

```
       {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "xxx",
                "cookies": "xxx"
            },
            "options": [
                "HomeAway.Disable",
                "Protect.MotionSensor.Disable"
            ],
            "platform": "Nest"
        },
```

**Expected behavior**
Should not crash.

Include with your bug report this version info:

```
# node --version
v20.11.1
# homebridge --version
1.8.5
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Running plugin version: v4.6.9

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

Debug startup logs attached. Unfortunately I can't reproduce on demand the issue. However I have error log for when it occurs:

```
0|homebrid | RangeError: Could not decode varint
0|homebrid |     at Object.read [as decode] (/usr/local/lib/node_modules/homebridge-nest/node_modules/varint/decode.js:17:13)
0|homebrid |     at ClientHttp2Stream.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/lib/nest-connection.js:648:44)
0|homebrid |     at ClientHttp2Stream.emit (node:events:518:28)
0|homebrid |     at addChunk (node:internal/streams/readable:559:12)
0|homebrid |     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
0|homebrid |     at ClientHttp2Stream.Readable.push (node:internal/streams/readable:390:5)
0|homebrid |     at Http2Stream.onStreamRead (node:internal/stream_base_commons:190:23)
0|homebrid | [11/10/2024, 7:53:27 PM] RangeError: Could not decode varint
0|homebrid |     at Object.read [as decode] (/usr/local/lib/node_modules/homebridge-nest/node_modules/varint/decode.js:17:13)
0|homebrid |     at ClientHttp2Stream.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/lib/nest-connection.js:648:44)
0|homebrid |     at ClientHttp2Stream.emit (node:events:518:28)
0|homebrid |     at addChunk (node:internal/streams/readable:559:12)
0|homebrid |     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
0|homebrid |     at ClientHttp2Stream.Readable.push (node:internal/streams/readable:390:5)
0|homebrid |     at Http2Stream.onStreamRead (node:internal/stream_base_commons:190:23)
```
[homebridge-startup-debug.log](https://github.com/user-attachments/files/17701094/homebridge-startup-debug.log)

**Comment by ValoV83** [comment]
I'm also having this error.

**Comment by vectronic** [comment]
A bit lame to automatically mark as stale because there has been no response. But anyway I have given up on the plugin because of this issue.

**Comment by ValoV83** [comment]
> A bit lame to automatically mark as stale because there has been no response. But anyway I have given up on the plugin because of this issue.

Could I ask you what plugin are you using as a replacement?

**Comment by vectronic** [comment]
I was only using it for nest protect. And for this reason I just rely on the nest app.

**Comment by ValoV83** [comment]
> I was only using it for nest protect. And for this reason I just rely on the nest app.

No worries. Thanks replying, just need to try and find a suitable replacement nest plugin that will support Homebridge 2.0

**Comment by shorbachuk** [comment]
+1 the child bridge crashes. I have nest protect and t-stats

**Comment by ValoV83** [comment]
Issue till not resolved @chrisjshull would really appreciate a resolution to this problem.

**Comment by ValoV83** [comment]
With the release of homebridge-nest v4.6.10 the bug appears to have been fixed for me. My homebridge instance hasn't crashed since the update.

**Comment by ValoV83** [comment]
Update: Crashes have resumed unfortunately.

[31/03/2025, 11:36:48] RangeError: Could not decode varint
    at Object.read [as decode] (/var/lib/homebridge/node_modules/homebridge-nest/node_modules/varint/decode.js:17:13)
    at ClientHttp2Stream.<anonymous> (/var/lib/homebridge/node_modules/homebridge-nest/lib/nest-connection.js:647:44)
    at ClientHttp2Stream.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at ClientHttp2Stream.Readable.push (node:internal/streams/readable:392:5)
    at Http2Stream.onStreamRead (node:internal/stream_base_commons:189:23)
[31/03/2025, 11:36:48] Got SIGTERM, shutting down Homebridge...
[31/03/2025, 11:36:53] [HB Supervisor] Homebridge process ended. Code: 143, signal: null.
[31/03/2025, 11:36:58] [HB Supervisor] Restarting Homebridge...
[31/03/2025, 11:36:58] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution.
[31/03/2025, 11:36:58] [HB Supervisor] Started Homebridge v1.9.0 with PID: 674502.

**Comment by DigitalFokus** [comment]
I have the same issue as well:

[4/6/2025, 6:09:10 AM] RangeError: Could not decode varint
    at Object.read [as decode] (/homebridge/node_modules/homebridge-nest/node_modules/varint/decode.js:17:13)
    at ClientHttp2Stream.<anonymous> (/homebridge/node_modules/homebridge-nest/lib/nest-connection.js:647:44)
    at ClientHttp2Stream.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at ClientHttp2Stream.Readable.push (node:internal/streams/readable:392:5)
    at Http2Stream.onStreamRead (node:internal/stream_base_commons:189:23)
[4/6/2025, 6:09:10 AM] Got SIGTERM, shutting down Homebridge...
[4/6/2025, 6:09:15 AM] [HB Supervisor] Homebridge process ended. Code: 143, signal: null.
[4/6/2025, 6:09:20 AM] [HB Supervisor] Restarting Homebridge...
[4/6/2025, 6:09:20 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution.
[4/6/2025, 6:09:20 AM] [HB Supervisor] Started Homebridge v1.9.0 with PID: 21467.

**Comment by MorelloCherry** [comment]
Encountered this issue first time today. The plugin restarted and worked from that point onwards

```
[06/04/2025, 20:59:16] [Nest] initing home_away_sensor "Home Occupied": deviceId: 9cd81190-bd3f-11ef-b901-0a61fe658a11 structureId: 9cd81190-bd3f-11ef-b901-0a61fe658a11

/var/lib/homebridge/node_modules/homebridge-nest/node_modules/varint/decode.js:17
      throw new RangeError('Could not decode varint')
            ^
RangeError: Could not decode varint
    at Object.read [as decode] (/var/lib/homebridge/node_modules/homebridge-nest/node_modules/varint/decode.js:17:13)
    at ClientHttp2Stream.<anonymous> (/var/lib/homebridge/node_modules/homebridge-nest/lib/nest-connection.js:647:44)
    at ClientHttp2Stream.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at ClientHttp2Stream.Readable.push (node:internal/streams/readable:392:5)
    at Http2Stream.onStreamRead (node:internal/stream_base_commons:189:23)
[06/04/2025, 22:59:14] [Nest] Child bridge process ended
[06/04/2025, 22:59:14] [Nest] Process Ended. Code: 1, Signal: null
[06/04/2025, 22:59:21] [Nest] Restarting Process...
```

In my case I did not interact with the plugin at this time and no issues with the ISP.

**Comment by ValoV83** [comment]
Issue still not resolved @chrisjshull would really appreciate a resolution to this problem.

**Comment by Fish2** [comment]
im also getting this error 

```
/homebridge/node_modules/homebridge-nest/node_modules/varint/decode.js:17
      throw new RangeError('Could not decode varint')
            ^
RangeError: Could not decode varint
    at Object.read [as decode] (/homebridge/node_modules/homebridge-nest/node_modules/varint/decode.js:17:13)
    at ClientHttp2Stream.<anonymous> (/homebridge/node_modules/homebridge-nest/lib/nest-connection.js:647:44)
    at ClientHttp2Stream.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at ClientHttp2Stream.Readable.push (node:internal/streams/readable:392:5)
    at Http2Stream.onStreamRead (node:internal/stream_base_commons:189:23)
```

**Comment by vectronic** [comment]
Oh well…

**Comment by tbaur** [comment]
Reopened via #742/#725 — framing fix in https://github.com/chrisjshull/homebridge-nest/pull/744 (also see #741).
