### ISSUE TITLE
Firebase Error when adjusting thermostat

### ISSUE THREAD

**Issue by cmb991** [chrisjshull/homebridge-nest#71]
Fresh install on raspberry pi homebridge.  Was working originally.  Shut down homebridge and reopened

```
[11/5/2018, 6:44:55 AM] Homebridge is running on port 51826.
[11/5/2018, 6:45:05 AM] [Nest] Queuing to set temperature 16.1
FIREBASE WARNING: set at /devices/thermostats/eOBa9KOTS0cTO_9Q8m3wXnj8QTYm1_vU/target_temperature_f failed: Thermostat is not online 
[11/5/2018, 6:45:10 AM] [Nest] Temperature set to 16.1 { Error: THERMOSTAT IS NOT ONLINE: {"error":"Thermostat is not online","type":"https://developer.nest.com/documentation/cloud/error-messages#not-online","message":"Thermostat is not online","instance":"99228be4-7d05-443c-85e2-e6eaf6214c23"}
    at /usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:226:115
    at ec (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:52:165)
    at Pi (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:226:23)
    at /usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:221:404
    at /usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:184:355
    at Rh.h.Jd (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:186:104)
    at Fh.Jd (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:176:364)
    at wh.Jg (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:174:280)
    at zh (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:168:464)
    at Client.Ka.onmessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:167:321)
    at Client.dispatchEvent (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
    at Client._receiveMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
    at Client.<anonymous> (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
    at Client.emit (events.js:187:15)
    at Client.<anonymous> (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
    at pipe (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
    at Pipeline._loop (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)
    at Pipeline.processIncomingMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)
    at Extensions.processIncomingMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
    at Client._emitMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
    at Client._emitFrame (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
    at Client.parse (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)
  cause:
   { Error: THERMOSTAT IS NOT ONLINE: {"error":"Thermostat is not online","type":"https://developer.nest.com/documentation/cloud/error-messages#not-online","message":"Thermostat is not online","instance":"99228be4-7d05-443c-85e2-e6eaf6214c23"}
       at /usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:226:115
       at ec (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:52:165)
       at Pi (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:226:23)
       at /usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:221:404
       at /usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:184:355
       at Rh.h.Jd (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:186:104)
       at Fh.Jd (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:176:364)
       at wh.Jg (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:174:280)
       at zh (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:168:464)
       at Client.Ka.onmessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:167:321)
       at Client.dispatchEvent (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
       at Client._receiveMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
       at Client.<anonymous> (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
       at Client.emit (events.js:187:15)
       at Client.<anonymous> (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
       at pipe (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
       at Pipeline._loop (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)
       at Pipeline.processIncomingMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)
       at Extensions.processIncomingMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
       at Client._emitMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
       at Client._emitFrame (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
       at Client.parse (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18) code: 'THERMOSTAT IS NOT ONLINE' },
  isOperational: true,
  code: 'THERMOSTAT IS NOT ONLINE' }


```

**Comment by afit** [comment]
That's an error from Nest stating that your thermostat is not online. The issue is between your device and Nest's servers. You can [read more here](https://developers.nest.com/reference/error-messages#thermostat_is_not_online) about that error code.

**Comment by adriancable** [comment]
homebridge-nest 3.0.0 no longer uses Firebase so all should be OK.
