### ISSUE TITLE
Temperature range lock gives errors

### ISSUE THREAD

**Issue by dodavies** [chrisjshull/homebridge-nest#74]
If a temperature range is set within nest which locks the thermostat and homebridge tries to change outside of limits an error output occurs, it isn't very friendly

FIREBASE WARNING: set at /devices/thermostats/dI4xtls81dGde7fPLHX6MHLLTj-vvXce/target_temperature_c failed: Temperature C '%s' is too high for lock temperature '%s'
[2018-12-10 13:07:04] [Nest] Temperature set to 21 { Error: TEMPERATURE C '%S' IS TOO HIGH FOR LOCK TEMPERATURE '%S': {"error":"Temperature C '21.0' is too high for lock temperature '20.5'","type":"https://developer.nest.com/documentation/cloud/error-messages#high-c-value-4-lock","message":"Temperature C '21.0' is too high for lock temperature '20.5'","instance":"11111111-1111-1111-1111-ab1111141011","details":{"tempC":"21.0","highLockTemp":"20.5"}}
    at /usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:226:115
    at ec (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:52:165)
    at Pi (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:226:23)
    at /usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:221:404
    at /usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:184:355
    at Rh.h.Jd (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:186:104)
    at Fh.Jd (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:176:364)
    at wh.Jg (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:174:280)
    at zh (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:168:464)
    at Client.Ka.onmessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:167:321)
    at Client.dispatchEvent (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
    at Client._receiveMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
    at Client.<anonymous> (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
    at emitOne (events.js:121:20)
    at Client.emit (events.js:211:7)
    at Client.<anonymous> (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
    at pipe (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
    at Pipeline._loop (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)
    at Pipeline.processIncomingMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)
    at Extensions.processIncomingMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
    at Client._emitMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
    at Client._emitFrame (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
  cause:
   { Error: TEMPERATURE C '%S' IS TOO HIGH FOR LOCK TEMPERATURE '%S': {"error":"Temperature C '21.0' is too high for lock temperature '20.5'","type":"https://developer.nest.com/documentation/cloud/error-messages#high-c-value-4-lock","message":"Temperature C '21.0' is too high for lock temperature '20.5'","instance":"snippedfor privacy ","details":{"tempC":"21.0","highLockTemp":"20.5"}}
    at /usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:226:115
    at ec (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:52:165)
    at Pi (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:226:23)
    at /usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:221:404
    at /usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:184:355
    at Rh.h.Jd (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:186:104)
    at Fh.Jd (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:176:364)
    at wh.Jg (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:174:280)
    at zh (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:168:464)
    at Client.Ka.onmessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:167:321)
    at Client.dispatchEvent (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
    at Client._receiveMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
    at Client.<anonymous> (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
    at emitOne (events.js:121:20)
    at Client.emit (events.js:211:7)
    at Client.<anonymous> (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
    at pipe (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
    at Pipeline._loop (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)
    at Pipeline.processIncomingMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)
    at Extensions.processIncomingMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
    at Client._emitMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
    at Client._emitFrame (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
     code: 'TEMPERATURE C \'%S\' IS TOO HIGH FOR LOCK TEMPERATURE \'%S\'' },
  isOperational: true,
  code: 'TEMPERATURE C \'%S\' IS TOO HIGH FOR LOCK TEMPERATURE \'%S\'' }

**Comment by adriancable** [comment]
The error is scary but the HomeKit UI should work OK. (the temperature read-out should revert back to the set value.)
